const fs=require('fs');
const TOKEN=process.env.TELEGRAM_TOKEN,CHAT=process.env.TELEGRAM_CHAT_ID,FILE='./xauusd_m5.json',STATE='./state_v2.json';
const MIN_SCORE=7; const FIBS=[0.236,0.382,0.5,0.618,0.65,0.705,0.786,0.886];
const load=(f,d)=>{try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):d}catch{return d}};
const save=(f,x)=>fs.writeFileSync(f,JSON.stringify(x,null,2));
function normalizeTs(ts){let x=Number(ts);if(!Number.isFinite(x))return null;if(x<1e11)x*=1000;return x}
const candles=load(FILE,[]).map(c=>({time:normalizeTs(c.time),open:+c.open,high:+c.high,low:+c.low,close:+c.close,volume:+c.volume||0})).filter(c=>c.time&&[c.open,c.high,c.low,c.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time);
if(candles.length<1200)throw Error(`Need >=1200 M5 candles, got ${candles.length}`); const closed=candles.slice(0,-1);
function agg(a,min){const step=min*60000,o=[];for(const c of a){const t=Math.floor(c.time/step)*step,x=o.at(-1);if(!x||x.time!==t)o.push({time:t,open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume});else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close;x.volume+=c.volume}}return o}
function ema(a,len){if(a.length<len)return null;let e=a[0].close,k=2/(len+1);for(let i=1;i<a.length;i++)e+=(a[i].close-e)*k;return e}
function atr(a,len=14){if(a.length<len+1)return null;let tr=[];for(let i=1;i<a.length;i++)tr.push(Math.max(a[i].high-a[i].low,Math.abs(a[i].high-a[i-1].close),Math.abs(a[i].low-a[i-1].close)));return tr.slice(-len).reduce((s,x)=>s+x,0)/len}
function trend(a){const e20=ema(a,20),e50=ema(a,50),c=a.at(-1)?.close;if(!e20||!e50||c==null)return'UNKNOWN';return c>e20&&e20>e50?'BULLISH':c<e20&&e20<e50?'BEARISH':'RANGE'}
function fibConfluence(a,dir,atrv){const w=a.slice(-80),hi=Math.max(...w.map(x=>x.high)),lo=Math.min(...w.map(x=>x.low)),span=hi-lo;if(span<atrv*3)return{score:0,level:null,price:null,levels:{}};const levels={};FIBS.forEach(f=>levels[f]=dir==='BUY'?hi-span*f:lo+span*f);const p=a.at(-1).close;let best=null,bestDist=Infinity;for(const f of FIBS){const d=Math.abs(p-levels[f]);if(d<bestDist){bestDist=d;best=f}}const dist=Math.abs(p-levels[best]);let score=dist<=atrv*.35?2:dist<=atrv*.7?1:0;if([.618,.65,.705,.786,.886].includes(best)&&dist<=atrv*.7)score++;return{score,level:best,price:levels[best],levels,hi,lo}}
function signalAt(i){const a=closed.slice(0,i+1);if(a.length<100)return null;const m15=agg(a,15),h1=agg(a,60),h4=agg(a,240);if(h1.length<50||h4.length<20)return null;const t4=trend(h4),t1=trend(h1),t15=trend(m15),c=a.at(-1),atrv=atr(a);if(!atrv)return null;const p=a.slice(-7,-1),ph=Math.max(...p.map(x=>x.high)),pl=Math.min(...p.map(x=>x.low)),range=Math.max(c.high-c.low,1e-9),body=Math.abs(c.close-c.open);const disp=body/range>=.5&&range>=atrv*.65,bb=c.close>ph,bs=c.close<pl,swb=a.slice(-5).some(x=>x.low<pl&&x.close>pl),sws=a.slice(-5).some(x=>x.high>ph&&x.close<ph);const z=a.slice(-21,-1),support=Math.min(...z.map(x=>x.low)),resistance=Math.max(...z.map(x=>x.high));const nearS=Math.abs(c.low-support)<=atrv*.45||(c.low<=support+atrv*.25&&c.close>support),nearR=Math.abs(c.high-resistance)<=atrv*.45||(c.high>=resistance-atrv*.25&&c.close<resistance);const rejB=nearS&&c.close>c.open&&c.close>support,rejS=nearR&&c.close<c.open&&c.close<resistance;const q=a.slice(-4,-1),mssB=c.close>Math.max(...q.map(x=>x.high)),mssS=c.close<Math.min(...q.map(x=>x.low));const tb=t4==='BULLISH'&&t1==='BULLISH',tr=t4==='BEARISH'&&t1==='BEARISH';let dir=null,score=0,setup='';if(tb&&t15!=='BEARISH'&&(bb||swb)){dir='BUY';setup='TREND';score=4+(bb?2:0)+(swb?1:0)+(disp?1:0)}else if(tr&&t15!=='BULLISH'&&(bs||sws)){dir='SELL';setup='TREND';score=4+(bs?2:0)+(sws?1:0)+(disp?1:0)}else if(rejB&&(mssB||disp)){dir='BUY';setup='SUPPORT_REJECTION';score=5+(mssB?2:0)+(disp?1:0)+(tb?1:0)}else if(rejS&&(mssS||disp)){dir='SELL';setup='RESISTANCE_REJECTION';score=5+(mssS?2:0)+(disp?1:0)+(tr?1:0)}else return null;const fib=fibConfluence(a,dir,atrv);score+=fib.score;if(score<MIN_SCORE)return null;const entry=c.close,swingL=Math.min(...a.slice(-12).map(x=>x.low)),swingH=Math.max(...a.slice(-12).map(x=>x.high));let sl=dir==='BUY'?Math.min(swingL,entry-atrv*.9):Math.max(swingH,entry+atrv*.9);let risk=Math.abs(entry-sl);risk=Math.max(atrv*.5,Math.min(atrv*2.5,risk));sl=dir==='BUY'?entry-risk:entry+risk;return{direction:dir,setup,entry,sl,tp1:dir==='BUY'?entry+risk:entry-risk,tp2:dir==='BUY'?entry+risk*2:entry-risk*2,score,candleTime:c.time,h4:t4,h1:t1,m15:t15,breakout:dir==='BUY'?bb:bs,sweep:dir==='BUY'?swb:sws,displacement:disp,mss:dir==='BUY'?mssB:mssS,fib,fibLevel:fib.level,atr:atrv}}
let found=null;for(let i=Math.max(100,closed.length-36);i<closed.length;i++){const s=signalAt(i);if(s)found=s}console.log(`V5 SCAN: ${Math.min(36,closed.length-100)} recent closed M5 candles`);if(!found){console.log('NO SIGNAL: no qualifying setup with trend/support/resistance + Fibonacci confluence');process.exit(0)}console.log('SIGNAL CANDIDATE',JSON.stringify(found));const state=load(STATE,{}),key=`${found.direction}|${found.setup}|${found.candleTime}|${found.entry.toFixed(2)}|${found.sl.toFixed(2)}`;if(state.lastSignalKey===key){console.log('DUPLICATE SIGNAL — not sent');process.exit(0)}
const iranTime=ts=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(normalizeTs(ts)));
async function send(s){if(!TOKEN||!CHAT)throw Error('Telegram secrets missing');const strength=s.score>=9?'🟢 STRONG':'🟡 VALID',setupName=s.setup==='SUPPORT_REJECTION'?'Support + Fib Rejection':s.setup==='RESISTANCE_REJECTION'?'Resistance + Fib Rejection':'Trend Continuation + Fib',fibName=s.fibLevel!=null?s.fibLevel.toFixed(3):'—';const text=`${s.direction==='BUY'?'🟢':'🔴'} XAUUSD ${s.direction} V5\n\n${strength} | Score ${s.score}/10\n📌 Setup: ${setupName}\n🕐 Signal: ${iranTime(s.candleTime)} (Iran)\n\nEntry: ${s.entry.toFixed(2)}\nSL: ${s.sl.toFixed(2)}\nTP1: ${s.tp1.toFixed(2)}\nTP2: ${s.tp2.toFixed(2)} (Extended Target)\n\nH4 ${s.h4} | H1 ${s.h1} | M15 ${s.m15}\nBreakout ${s.breakout?'✅':'❌'} | Sweep ${s.sweep?'✅':'❌'} | Displacement ${s.displacement?'✅':'❌'} | MSS ${s.mss?'✅':'❌'}\nFib: ${fibName} @ ${s.fib.price?s.fib.price.toFixed(2):'—'}\nFib levels: 0.236 | 0.382 | 0.500 | 0.618 | 0.650 | 0.705 | 0.786 | 0.886\nATR ${s.atr.toFixed(2)}\n\n⚠️ TP2 is a target, not a guarantee. Risk management mandatory.`;const r=await fetch(`https://api.telegram.org/bot${TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:CHAT,text})});if(!r.ok)throw Error(`Telegram HTTP ${r.status}: ${await r.text()}`)}
(async()=>{await send(found);state.lastSignalKey=key;state.lastSignalTime=new Date().toISOString();save(STATE,state);console.log('TELEGRAM: SIGNAL SENT')})().catch(e=>{console.error(e);process.exit(1)});