const fs=require('fs');
const TOKEN=process.env.TELEGRAM_TOKEN, CHAT=process.env.TELEGRAM_CHAT_ID;
const FILE='./xauusd_m5.json', STATE='./state_v2.json';
const MIN_SCORE=12;
const n=x=>Number.isFinite(Number(x))?Number(x):null;
const load=(f,d)=>{try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):d}catch{return d}};
const save=(f,x)=>fs.writeFileSync(f,JSON.stringify(x,null,2));
const candles=load(FILE,[]).map(c=>({time:n(c.time),open:n(c.open),high:n(c.high),low:n(c.low),close:n(c.close),volume:n(c.volume)||0})).filter(c=>c.time&&[c.open,c.high,c.low,c.close].every(v=>v!=null)).sort((a,b)=>a.time-b.time);
if(candles.length<1200)throw Error(`Need >=1200 M5 candles, got ${candles.length}`);
const d=candles.slice(-3000), closed=d.slice(0,-1);
function agg(a,m){const step=m*60000,o=[];for(const c of a){const t=Math.floor(c.time/step)*step,x=o.at(-1);if(!x||x.time!==t)o.push({time:t,open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume});else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close;x.volume+=c.volume}}return o}
function ema(a,l){if(a.length<l)return null;let e=a[0].close,k=2/(l+1);for(let i=1;i<a.length;i++)e+=(a[i].close-e)*k;return e}
function atr(a,l=14){if(a.length<l+1)return null;let z=[];for(let i=1;i<a.length;i++)z.push(Math.max(a[i].high-a[i].low,Math.abs(a[i].high-a[i-1].close),Math.abs(a[i].low-a[i-1].close)));return z.slice(-l).reduce((x,y)=>x+y,0)/l}
function swings(a,s=2){const h=[],l=[];for(let i=s;i<a.length-s;i++){let hi=1,lo=1;for(let j=i-s;j<=i+s;j++)if(j!==i){if(a[j].high>=a[i].high)hi=0;if(a[j].low<=a[i].low)lo=0}if(hi)h.push({i,p:a[i].high});if(lo)l.push({i,p:a[i].low})}return{h,l}}
function structure(a){const q=swings(a);if(q.h.length<3||q.l.length<3)return null;const h1=q.h.at(-2),h2=q.h.at(-1),l1=q.l.at(-2),l2=q.l.at(-1);return{trend:h2.p>h1.p&&l2.p>l1.p?'BULLISH':h2.p<h1.p&&l2.p<l1.p?'BEARISH':'RANGE',h1,h2,l1,l2}}
function bias(a){const s=structure(a);if(!s)return'UNKNOWN';const e20=ema(a,20),e50=ema(a,50),c=a.at(-1).close;if(s.trend==='BULLISH'&&c>e20&&e20>e50)return'BULLISH';if(s.trend==='BEARISH'&&c<e20&&e20<e50)return'BEARISH';return s.trend}
function fib(a,dir){const s=structure(a);if(!s)return null;const hi=s.h2.p,lo=s.l2.p,r=hi-lo;if(r<=0)return null;const lv={};for(const x of [0,.236,.382,.5,.618,.65,.705,.786,.886,1,1.272,1.414,1.618,2,2.618,3.618,4.236])lv[x]=dir==='BUY'?hi-r*x:lo+r*x;return{levels:lv,range:r}}
function zone(a,dir){for(let i=a.length-2;i>=Math.max(1,a.length-100);i--){const c=a[i];if(dir==='BUY'&&c.close<c.open)return{low:c.low,high:c.high,type:'OB'};if(dir==='SELL'&&c.close>c.open)return{low:c.low,high:c.high,type:'OB'}}return null}
function fvg(a,dir){for(let i=a.length-1;i>=Math.max(2,a.length-100);i--){const x=a[i-2],c=a[i];if(dir==='BUY'&&c.low>x.high)return{low:x.high,high:c.low,type:'FVG'};if(dir==='SELL'&&c.high<x.low)return{low:c.high,high:x.low,type:'FVG'}}return null}
function inZone(c,z){return z&&c.high>=z.low&&c.low<=z.high}
function events(a,idx,dir){const w=a.slice(Math.max(0,idx-12),idx+1),s=structure(a.slice(0,idx+1));if(!s)return null;const atrv=atr(a.slice(0,idx+1));if(!atrv)return null;const sweep=dir==='BUY'?w.some(x=>x.low<s.l2.p&&x.close>s.l2.p):w.some(x=>x.high>s.h2.p&&x.close<s.h2.p);const mss=dir==='BUY'?w.some((x,j)=>j>=3&&x.close>Math.max(...w.slice(0,j-1).map(y=>y.high))):w.some((x,j)=>j>=3&&x.close<Math.min(...w.slice(0,j-1).map(y=>y.low)));const disp=w.some(x=>{const r=Math.max(x.high-x.low,1e-9);return r>=atrv*.8&&Math.abs(x.close-x.open)/r>=.5&&(dir==='BUY'?x.close>x.open:x.close<x.open)});const b=w.some(x=>dir==='BUY'?x.close>s.h2.p:x.close<s.l2.p);return{s,atr:atrv,sweep,mss,disp,bos:b}}
function candidate(idx){const a=closed.slice(0,idx+1),m15=agg(a,15),h1=agg(a,60),h4=agg(a,240);if(m15.length<50||h1.length<50||h4.length<20)return null;const h4b=bias(h4),h1b=bias(h1),m15b=bias(m15),s=structure(a);if(!s)return null;let dir=null;if(h4b==='BULLISH'&&h1b==='BULLISH'&&m15b!=='BEARISH'&&s.trend==='BULLISH')dir='BUY';if(h4b==='BEARISH'&&h1b==='BEARISH'&&m15b!=='BULLISH'&&s.trend==='BEARISH')dir='SELL';if(!dir)return null;const e=events(a,idx,dir),c=a.at(-1),ob=zone(a,dir),fv=fvg(a,dir),z=fv||ob,ret=inZone(c,z),f=fib(a,dir),p=c.close;if(!e||!f)return null;let near=null,dist=Infinity;for(const x of [.618,.65,.705,.786,.886]){const q=Math.abs(p-f.levels[x]);if(q<dist){dist=q;near=x}}const fibOk=dist<=Math.max(f.range*.015,e.atr*.45,.30);let score=0;if(h4b===(dir==='BUY'?'BULLISH':'BEARISH'))score+=2;if(h1b===(dir==='BUY'?'BULLISH':'BEARISH'))score+=2;if(m15b===(dir==='BUY'?'BULLISH':'BEARISH'))score+=1;if(e.sweep)score+=2;if(e.mss)score+=2;if(e.bos)score+=1;if(ob)score+=1;if(fv)score+=1;if(ret)score+=1;if(e.disp)score+=2;if(fibOk)score+=1;if(score<MIN_SCORE||!e.sweep||!e.mss||!e.disp||!z||!ret)return null;const sl=dir==='BUY'?Math.min(z.low,e.s.l2.p)-e.atr*.15:Math.max(z.high,e.s.h2.p)+e.atr*.15,risk=Math.abs(p-sl);if(risk<e.atr*.45||risk>e.atr*2.2)return null;return{direction:dir,entry:p,sl,tp1:p+(dir==='BUY'?risk:-risk),tp2:p+(dir==='BUY'?risk*2:-risk*2),score,candleTime:c.time,h4:h4b,h1:h1b,m15:m15b,m5:s.trend,sweep:e.sweep,mss:e.mss,bos:e.bos,displacement:e.disp,ob:!!ob,fvg:!!fv,fibNear:near,atr:e.atr}}
let found=null;for(let i=Math.max(0,closed.length-24);i<closed.length;i++){const x=candidate(i);if(x)found=x}
let state=load(STATE,{});if(!found){console.log('NO HIGH QUALITY SETUP — scanned last 24 closed M5 candles with multi-candle SMC sequence.');process.exit(0)}
console.log('SIGNAL CANDIDATE',JSON.stringify(found));const key=`${found.direction}|${found.candleTime}|${found.entry.toFixed(2)}|${found.sl.toFixed(2)}`;if(state.lastSignalKey===key){console.log('DUPLICATE SIGNAL — not sent');process.exit(0)}
async function send(s){if(!TOKEN||!CHAT)throw Error('Telegram secrets missing');const text=`${s.direction==='BUY'?'🟢':'🔴'} XAUUSD ${s.direction} V5\n\nEntry: ${s.entry.toFixed(2)}\nSL: ${s.sl.toFixed(2)}\nTP1: ${s.tp1.toFixed(2)}\nTP2: ${s.tp2.toFixed(2)}\n\nH4 ${s.h4} | H1 ${s.h1} | M15 ${s.m15} | M5 ${s.m5}\nSweep ${s.sweep?'✅':'❌'} | MSS ${s.mss?'✅':'❌'} | BOS ${s.bos?'✅':'❌'}\nOB ${s.ob?'✅':'❌'} | FVG ${s.fvg?'✅':'❌'} | Displacement ${s.displacement?'✅':'❌'}\nFib ${s.fibNear} | Score ${s.score}\nATR ${s.atr.toFixed(2)}\n\n⚠️ Risk management mandatory.`;const r=await fetch(`https://api.telegram.org/bot${TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:CHAT,text})});if(!r.ok)throw Error(`Telegram HTTP ${r.status}: ${await r.text()}`)}
(async()=>{await send(found);state.lastSignalKey=key;state.lastSignalTime=new Date().toISOString();save(STATE,state);console.log('TELEGRAM: SIGNAL SENT')})().catch(e=>{console.error(e);process.exit(1)})