// ICT/SMC V8 — conservative, causal XAUUSD M5 signal engine.
// Every decision uses only candles available at the signal candle close.
function atr(d,n=14){if(d.length<n+1)return null;let tr=[];for(let i=1;i<d.length;i++)tr.push(Math.max(d[i].high-d[i].low,Math.abs(d[i].high-d[i-1].close),Math.abs(d[i].low-d[i-1].close)));return tr.slice(-n).reduce((a,b)=>a+b,0)/n}
function ema(d,n){if(d.length<n)return null;let k=2/(n+1),e=d[0].close;for(let i=1;i<d.length;i++)e+=(d[i].close-e)*k;return e}
function swingHigh(d,i,s=2){if(i<s||i>=d.length-s)return false;for(let j=i-s;j<=i+s;j++)if(j!==i&&d[j].high>=d[i].high)return false;return true}
function swingLow(d,i,s=2){if(i<s||i>=d.length-s)return false;for(let j=i-s;j<=i+s;j++)if(j!==i&&d[j].low<=d[i].low)return false;return true}
function swings(d){let h=[],l=[];for(let i=2;i<d.length-2;i++){if(swingHigh(d,i))h.push({i,p:d[i].high});if(swingLow(d,i))l.push({i,p:d[i].low})}return{h,l}}
function aggregate(d,min){let step=min*60000,o=[];for(const c of d){let t=Math.floor(c.time/step)*step,x=o.at(-1);if(!x||x.time!==t)o.push({time:t,open:c.open,high:c.high,low:c.low,close:c.close});else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close}}return o}
function bias15(d){let x=aggregate(d,15);if(x.length<50)return'UNKNOWN';// exclude the still-forming 15m candle
x=x.slice(0,-1);if(x.length<50)return'UNKNOWN';let e20=ema(x,20),e50=ema(x,50),c=x.at(-1).close;return c>e20&&e20>e50?'BULLISH':c<e20&&e20<e50?'BEARISH':'NEUTRAL'}
function fvgAt(d,i,dir){if(i<2)return null;let a=d[i-2],c=d[i];if(dir==='BUY'&&c.low>a.high)return{low:a.high,high:c.low,i};if(dir==='SELL'&&c.high<a.low)return{low:c.high,high:a.low,i};return null}
function freshFvg(d,dir,ms){for(let i=ms+1;i<=Math.min(ms+3,d.length-1);i++){let f=fvgAt(d,i,dir);if(!f)continue;let touched=false;for(let j=f.i+1;j<d.length-1;j++)if(d[j].low<=f.high&&d[j].high>=f.low){touched=true;break}if(!touched)return f}return null}
function overlap(c,z){return c&&z&&c.high>=z.low&&c.low<=z.high}
function rsi(d,n=14){if(d.length<n+1)return null;let g=0,l=0;for(let i=d.length-n;i<d.length;i++){let x=d[i].close-d[i-1].close;if(x>=0)g+=x;else l-=x}return l===0?100:100-100/(1+g/l)}
function analyzeV8(d){if(!Array.isArray(d)||d.length<220)return null;const c=d.at(-1),a=atr(d),b=bias15(d),s=swings(d);if(!a||b==='UNKNOWN'||b==='NEUTRAL'||s.h.length<3||s.l.length<3)return null;const dir=b==='BULLISH'?'BUY':'SELL';const ph=s.h.at(-2),pl=s.l.at(-2),ch=s.h.at(-1),cl=s.l.at(-1);if(dir==='BUY'?(ch.p<=ph.p||cl.p<=pl.p):(ch.p>=ph.p||cl.p>=pl.p))return null;
let sweep=null;for(let i=Math.max(4,d.length-7);i<d.length;i++){if(dir==='BUY'&&d[i].low<cl.p&&d[i].close>cl.p)sweep={i,level:cl.p};if(dir==='SELL'&&d[i].high>ch.p&&d[i].close<ch.p)sweep={i,level:ch.p}}if(!sweep)return null;
let ms=null;for(let i=sweep.i+1;i<=Math.min(d.length-1,sweep.i+4);i++){let x=d[i],body=Math.abs(x.close-x.open),rng=Math.max(x.high-x.low,1e-9),disp=body/rng>=.55&&rng>=a*.8;if(dir==='BUY'&&x.close>ph.p&&x.close>x.open&&disp){ms={i,level:ph.p};break}if(dir==='SELL'&&x.close<pl.p&&x.close<x.open&&disp){ms={i,level:pl.p};break}}if(!ms)return null;
const f=freshFvg(d,dir,ms.i);if(!f||!overlap(c,f))return null;const legLow=dir==='BUY'?sweep.level:ms.level,legHigh=dir==='BUY'?ms.level:sweep.level,rng=Math.abs(legHigh-legLow);if(rng<=0)return null;const ote={705:dir==='BUY'?legHigh-rng*.705:legLow+rng*.705,786:dir==='BUY'?legHigh-rng*.786:legLow+rng*.786};const tol=Math.max(rng*.10,a*.35);const fibOk=Math.min(Math.abs(c.close-ote[705]),Math.abs(c.close-ote[786]))<=tol;if(!fibOk)return null;const rv=rsi(d);if(rv==null|| (dir==='BUY'?(rv<48||rv>72):(rv<28||rv>52)))return null;const sl=dir==='BUY'?Math.min(sweep.level,f.low)-a*.2:Math.max(sweep.level,f.high)+a*.2,entry=c.close,risk=Math.abs(entry-sl);if(risk<a*.45||risk>a*2.2)return null;const tp1=dir==='BUY'?entry+risk:entry-risk,tp2=dir==='BUY'?entry+2*risk:entry-2*risk,tp3=dir==='BUY'?entry+3*risk:entry-3*risk;return{strategy:'ICT-V8',direction:dir,entry,sl,tp1,tp2,tp3,risk,score:10,m15:b,sweep:true,mss:true,displacement:true,fvg:true,ote:true,rsi:rv,atr:a,sweepIndex:sweep.i,mssIndex:ms.i,fvgIndex:f.i,candleTime:c.time,diagnostic:{causal:true,m15ClosedOnly:true,sweepLevel:sweep.level,structureHigh:ch.p,structureLow:cl.p,fvg:f,ote705:ote[705],ote786:ote[786]}}}
module.exports={analyzeV8};