function atr(d,len=14){if(d.length<len+1)return null;let s=0;for(let i=d.length-len;i<d.length;i++){const p=d[i-1],c=d[i];s+=Math.max(c.high-c.low,Math.abs(c.high-p.close),Math.abs(c.low-p.close))}return s/len}
function ema(d,len){if(d.length<len)return null;const k=2/(len+1);let e=d[0].close;for(let i=1;i<d.length;i++)e+=(d[i].close-e)*k;return e}
function m15(d){const m=[];for(const c of d){const t=Math.floor(c.time/900000)*900000,x=m.at(-1);if(!x||x.time!==t)m.push({time:t,open:c.open,high:c.high,low:c.low,close:c.close});else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close}}const last=d.at(-1)?.time;if(m.at(-1)?.time+900000>last)m.pop();if(m.length<12)return null;const h=[],l=[];for(let i=2;i<m.length-2;i++){let hi=true,lo=true;for(let j=1;j<=2;j++){if(m[i-j].high>=m[i].high||m[i+j].high>=m[i].high)hi=false;if(m[i-j].low<=m[i].low||m[i+j].low<=m[i].low)lo=false}if(hi&&i+2<m.length)h.push({i,p:m[i].high});if(lo&&i+2<m.length)l.push({i,p:m[i].low})}if(h.length<2||l.length<2)return null;const hh=h.at(-1).p>h.at(-2).p,hl=l.at(-1).p>l.at(-2).p,lh=h.at(-1).p<h.at(-2).p,ll=l.at(-1).p<l.at(-2).p;return{trend:hh&&hl?'BULLISH':lh&&ll?'BEARISH':'NEUTRAL',bars:m}}
function swings(d,s=2){const h=[],l=[];for(let i=s;i<d.length-s;i++){let hi=true,lo=true;for(let j=1;j<=s;j++){if(d[i-j].high>=d[i].high||d[i+j].high>=d[i].high)hi=false;if(d[i-j].low<=d[i].low||d[i+j].low<=d[i].low)lo=false}if(hi)h.push({i,p:d[i].high,confirmedAt:i+s});if(lo)l.push({i,p:d[i].low,confirmedAt:i+s})}return{h,l}}
function fvgAt(d,dir,i){if(i<2)return null;const a=d[i-2],c=d[i];if(dir==='BUY'&&c.low>a.high)return{low:a.high,high:c.low,i,type:'FVG'};if(dir==='SELL'&&c.high<a.low)return{low:c.high,high:a.low,i,type:'FVG'};return null}
function freshFvg(d,dir,start,end){for(let i=Math.max(2,start);i<=end;i++){const f=fvgAt(d,dir,i);if(!f)continue;let fresh=true;for(let j=i+1;j<=end;j++)if(d[j].low<=f.high&&d[j].high>=f.low){fresh=false;break}if(fresh)return f}return null}
function ob(d,dir,end){for(let i=end-1;i>=Math.max(0,end-12);i--){const c=d[i];if(dir==='BUY'&&c.close<c.open)return{low:c.low,high:c.high,i,type:'OB'};if(dir==='SELL'&&c.close>c.open)return{low:c.low,high:c.high,i,type:'OB'}}return null}
function overlap(a,b){return !!(a&&b&&a.high>=b.low&&a.low<=b.high)}
function candleConfirm(d,dir){if(d.length<2)return false;const p=d.at(-2),c=d.at(-1);const body=Math.abs(c.close-c.open),range=Math.max(c.high-c.low,1e-9),upper=c.high-Math.max(c.open,c.close),lower=Math.min(c.open,c.close)-c.low;const engulf=dir==='BUY'?c.close>c.open&&p.close<p.open&&c.open<=p.close&&c.close>=p.open:c.close<c.open&&p.close>p.open&&c.open>=p.close&&c.close<=p.open;const pin=dir==='BUY'?lower>=body*2&&upper<=body:upper>=body*2&&lower<=body;return engulf||pin}
function rrScore(){return 5}
function analyzeV8Candidate(d){if(d.length<220)return null;const c=d.at(-1),end=d.length-1,a=atr(d),base=atr(d,50),bias=m15(d),s=swings(d,2);if(!a||!base||!bias||bias.trend==='NEUTRAL')return null;const dir=bias.trend==='BULLISH'?'BUY':'SELL';const sess=((h)=>h>=7&&h<11?'LONDON':h>=13&&h<17?'NEW_YORK':null)(new Date(c.time).getUTCHours()+new Date(c.time).getUTCMinutes()/60);if(!sess)return null;const hs=s.h.filter(x=>x.confirmedAt<=end),ls=s.l.filter(x=>x.confirmedAt<=end);if(hs.length<2||ls.length<2)return null;const lastH=hs.at(-1),lastL=ls.at(-1);let bos=null;const breakLevel=dir==='BUY'?lastH.p:lastL.p;for(let i=Math.max(0,end-6);i<=end;i++){if(dir==='BUY'&&d[i].close>breakLevel){bos={i};break}if(dir==='SELL'&&d[i].close<breakLevel){bos={i};break}}if(!bos)return null;const f=freshFvg(d,dir,Math.max(2,bos.i-2),end),o=ob(d,dir,bos.i);const fvgOK=overlap(c,f),obOK=overlap(c,o);if(!fvgOK&&!obOK)return null;const atrRatio=a/base;let atrPts=atrRatio<.5?0:15;const confirm=candleConfirm(d,dir);let score=25+20+(fvgOK||obOK?25:0)+atrPts+(confirm?10:0)+rrScore();if(score<70)return null;const zone=fvgOK?f:o;const buffer=a*.2;const sl=dir==='BUY'?zone.low-buffer:zone.high+buffer;const entry=c.close,risk=Math.abs(entry-sl);if(!(risk>0))return null;const tp1=dir==='BUY'?entry+risk:entry-risk,tp2=dir==='BUY'?entry+1.5*risk:entry-1.5*risk,tp3=dir==='BUY'?entry+2*risk:entry-2*risk;return{version:'V8-CANDIDATE',direction:dir,entry,sl,tp1,tp2,tp3,score,atr:a,atrRatio:+atrRatio.toFixed(3),m15:bias.trend,session:sess,bos:true,choch:false,fvg:fvgOK,ob:obOK,confirmation:confirm,rr:1.5,candleTime:c.time,diagnostic:{causal:true,m15ClosedOnly:true,confirmedSwingDelay:2,freshFvgBoundedToCurrentBar:true,noSweepRequired:true,newsBlock:false,scoreBreakdown:{bos:25,bias:20,zone:25,atr:atrPts,confirmation:confirm?10:0,rr:5}}}}
module.exports={analyzeV8Candidate};
