function ema(d,len){if(d.length<len)return null;const k=2/(len+1);let e=d[0].close;for(let i=1;i<d.length;i++)e+=(d[i].close-e)*k;return e}
function atr(d,len=14){if(d.length<len+1)return null;let s=0;for(let i=d.length-len;i<d.length;i++){const p=d[i-1],c=d[i];s+=Math.max(c.high-c.low,Math.abs(c.high-p.close),Math.abs(c.low-p.close))}return s/len}
function rsi(d,len=14){if(d.length<len+1)return null;let g=0,l=0;for(let i=d.length-len;i<d.length;i++){const x=d[i].close-d[i-1].close;if(x>=0)g+=x;else l-=x}return l===0?100:100-100/(1+g/l)}
// A pivot is usable only after its confirmation bars have closed. No centered/future read at signal time.
function confirmedSwings(d,s=2){const h=[],l=[];for(let i=s;i<d.length-s;i++){let hi=true,lo=true;for(let j=1;j<=s;j++){if(d[i-j].high>=d[i].high||d[i+j].high>=d[i].high)hi=false;if(d[i-j].low<=d[i].low||d[i+j].low<=d[i].low)lo=false}if(hi)h.push({i,p:d[i].high,confirmedAt:i+s});if(lo)l.push({i,p:d[i].low,confirmedAt:i+s})}return{h,l}}
function m15Closed(d){const m=[];for(const c of d){const t=Math.floor(c.time/900000)*900000,x=m.at(-1);if(!x||x.time!==t)m.push({time:t,open:c.open,high:c.high,low:c.low,close:c.close});else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close}}const last=d.at(-1)?.time;if(!m.length)return{trend:'UNKNOWN',bars:m};if(m.at(-1).time+900000>last)m.pop();if(m.length<50)return{trend:'UNKNOWN',bars:m};const e20=ema(m,20),e50=ema(m,50),c=m.at(-1).close;return{trend:c>e20&&e20>e50?'BULLISH':c<e20&&e20<e50?'BEARISH':'NEUTRAL',bars:m}}
function fvgAt(d,dir,i){if(i<2)return null;const a=d[i-2],c=d[i];if(dir==='BUY'&&c.low>a.high)return{low:a.high,high:c.low,type:'BULLISH FVG',i};if(dir==='SELL'&&c.high<a.low)return{low:c.high,high:a.low,type:'BEARISH FVG',i};return null}
function freshFvg(d,dir,formationIndex,currentIndex){for(let i=Math.max(formationIndex,2);i<=currentIndex;i++){const f=fvgAt(d,dir,i);if(!f)continue;let fresh=true;for(let j=f.i+1;j<=currentIndex;j++){if(d[j].low<=f.high&&d[j].high>=f.low){fresh=false;break}}if(fresh)return f}return null}
function overlap(a,b){return !!(a&&b&&a.high>=b.low&&a.low<=b.high)}
function opposingOB(d,dir,ms){for(let i=ms-1;i>=Math.max(0,ms-10);i--){const c=d[i];if(dir==='BUY'&&c.close<c.open)return{low:c.low,high:c.high,i,type:'BULLISH OB'};if(dir==='SELL'&&c.close>c.open)return{low:c.low,high:c.high,i,type:'BEARISH OB'}}return null}
function ote(dir,low,high,c,a){const r=high-low;if(!(r>0))return null;const levels={};for(const x of [.618,.705,.786])levels[x]=dir==='BUY'?high-r*x:low+r*x;const dist=Math.min(Math.abs(c.close-levels[.705]),Math.abs(c.close-levels[.786]));return{levels,ok:dist<=Math.max(r*.08,a*1.25),dist}}
function analyzeV8(d){if(d.length<220)return null;const c=d.at(-1),end=d.length-1,a=atr(d),rv=rsi(d),ht=m15Closed(d),s=confirmedSwings(d,2);if(!a||rv==null||ht.trend==='UNKNOWN'||ht.trend==='NEUTRAL')return null;const dir=ht.trend==='BULLISH'?'BUY':'SELL';const usableH=s.h.filter(x=>x.confirmedAt<=end),usableL=s.l.filter(x=>x.confirmedAt<=end);const preH=usableH.at(-2),curH=usableH.at(-1),preL=usableL.at(-2),curL=usableL.at(-1);if(!preH||!curH||!preL||!curL)return null;const structure=dir==='BUY'?curH.p>preH.p&&curL.p>preL.p:curH.p<preH.p&&curL.p<preL.p;if(!structure)return null;const sweepLevel=dir==='BUY'?curL.p:curH.p;let sweep=null;for(let i=Math.max(0,end-5);i<=end;i++){if(dir==='BUY'&&d[i].low<sweepLevel&&d[i].close>sweepLevel)sweep={i,level:sweepLevel};if(dir==='SELL'&&d[i].high>sweepLevel&&d[i].close<sweepLevel)sweep={i,level:sweepLevel}}if(!sweep)return null;const breakLevel=dir==='BUY'?curH.p:curL.p;let mss=null;for(let i=sweep.i+1;i<=Math.min(end,sweep.i+4);i++){const x=d[i],rng=Math.max(x.high-x.low,.00001),body=Math.abs(x.close-x.open),disp=body/rng>=.6&&rng>=a*.9;if(dir==='BUY'&&x.close>breakLevel&&x.close>x.open&&disp){mss={i};break}if(dir==='SELL'&&x.close<breakLevel&&x.close<x.open&&disp){mss={i};break}}if(!mss)return null;const f=freshFvg(d,dir,mss.i,end);if(!f||!overlap(c,f))return null;const ob=opposingOB(d,dir,mss.i);if(!ob||!overlap(ob,f))return null;const legLow=dir==='BUY'?sweep.level:mss.i===undefined?breakLevel:breakLevel;const legHigh=dir==='BUY'?breakLevel:sweep.level;const fib=ote(dir,Math.min(legLow,legHigh),Math.max(legLow,legHigh),c,a);if(!fib||!fib.ok)return null;const rsiOK=dir==='BUY'?rv>=52&&rv<=68:rv>=32&&rv<=48;if(!rsiOK)return null;const age=end-mss.i;if(age>2)return null;const sl=dir==='BUY'?Math.min(sweep.level,f.low,ob.low)-a*.2:Math.max(sweep.level,f.high,ob.high)+a*.2;const entry=c.close,risk=Math.abs(entry-sl);if(risk<a*.5||risk>a*1.8)return null;const tp2=dir==='BUY'?entry+2*risk:entry-2*risk;const score=9+(fib.ok?1:0)+(rv>=55&&rv<=65?1:0)+(age<=1?1:0);return{version:'V8',direction:dir,entry,sl,tp1:dir==='BUY'?entry+risk:entry-risk,tp2,score,atr:a,rsi:rv,m15:ht.trend,structure:dir,bos:true,mss:true,sweep:true,ob:true,fvg:true,confirmation:true,displacement:true,fibNear:Math.abs(c.close-fib.levels[.705])<=Math.abs(c.close-fib.levels[.786])?.705:.786,fibLevels:fib.levels,candleTime:c.time,diagnostic:{causal:true,confirmedSwingDelay:2,m15ClosedOnly:true,freshFvgBoundedToCurrentBar:true,noFutureBars:true,sweepIndex:sweep.i,mssIndex:mss.i,fvgIndex:f.i,obIndex:ob.i,displacementAge:age}}}
module.exports={analyzeV8};