function ema(d,len){if(d.length<len)return null;const k=2/(len+1);let e=d[0].close;for(let i=1;i<d.length;i++)e+=(d[i].close-e)*k;return e}
function atr(d,len=14){if(d.length<len+1)return null;let t=[];for(let i=1;i<d.length;i++)t.push(Math.max(d[i].high-d[i].low,Math.abs(d[i].high-d[i-1].close),Math.abs(d[i].low-d[i-1].close)));return t.slice(-len).reduce((a,b)=>a+b,0)/len}
function rsi(d,len=14){if(d.length<len+1)return null;let g=0,l=0;for(let i=d.length-len;i<d.length;i++){let x=d[i].close-d[i-1].close;if(x>=0)g+=x;else l-=x}return l===0?100:100-100/(1+g/l)}
function swH(d,i,s=2){if(i<s||i>=d.length-s)return false;for(let j=i-s;j<=i+s;j++)if(j!==i&&d[j].high>=d[i].high)return false;return true}
function swL(d,i,s=2){if(i<s||i>=d.length-s)return false;for(let j=i-s;j<=i+s;j++)if(j!==i&&d[j].low<=d[i].low)return false;return true}
function swings(d){let h=[],l=[];for(let i=2;i<d.length-2;i++){if(swH(d,i))h.push({i,p:d[i].high});if(swL(d,i))l.push({i,p:d[i].low})}return{h,l}}
function m15(d){let m=[];for(const c of d){let t=Math.floor(c.time/900000)*900000,x=m.at(-1);if(!x||x.time!==t)m.push({time:t,open:c.open,high:c.high,low:c.low,close:c.close});else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close}}if(m.length<50)return{trend:'UNKNOWN',bars:m};let e20=ema(m,20),e50=ema(m,50),c=m.at(-1).close;return{trend:c>e20&&e20>e50?'BULLISH':c<e20&&e20<e50?'BEARISH':'NEUTRAL',bars:m}}
function nearestFib(d,dir,lo,hi){let range=hi-lo;if(!(range>0))return null;let levels={};for(const x of [.618,.705,.786])levels[x]=dir==='BUY'?hi-range*x:lo+range*x;let c=d.at(-1),best=null,dist=Infinity;for(const x of [.618,.705,.786]){let q=Math.abs(c.close-levels[x]);if(q<dist){dist=q;best=x}}return{levels,best,dist,ok:dist<=Math.max(range*.035,atr(d)*.35)}}
function findSweep(d,dir,h,l){let end=d.length-1,start=Math.max(0,end-4);for(let i=end;i>=start;i--){let c=d[i];if(dir==='BUY'&&c.low<l.p&&c.close>l.p)return{i,level:l.p};if(dir==='SELL'&&c.high>h.p&&c.close<h.p)return{i,level:h.p}}return null}
function mssAfterSweep(d,dir,si,h,l){let end=d.length-1;for(let i=si+1;i<=Math.min(end,si+3);i++){let c=d[i];if(dir==='BUY'&&c.close>h.p&&c.close>c.open)return{i,level:h.p};if(dir==='SELL'&&c.close<l.p&&c.close<c.open)return{i,level:l.p}}return null}
function fvgAt(d,dir,i){if(i<2)return null;let a=d[i-2],c=d[i];if(dir==='BUY'&&c.low>a.high)return{low:a.high,high:c.low,type:'BULLISH FVG',i};if(dir==='SELL'&&c.high<a.low)return{low:c.high,high:a.low,type:'BEARISH FVG',i};return null}
function freshFvg(d,dir,from){for(let i=Math.max(2,from);i<=d.length-1;i++){let f=fvgAt(d,dir,i);if(f){let touched=false;for(let j=i+1;j<d.length;j++)if(d[j].low<=f.high&&d[j].high>=f.low){touched=true;break}if(!touched)return f}}return null}
function inZone(c,z){return z&&c.high>=z.low&&c.low<=z.high}
function analyzeV71(d){if(d.length<160)return null;let c=d.at(-1),p=d.at(-2),a=atr(d),rv=rsi(d),s=swings(d),ht=m15(d);if(!a||!rv||ht.trend==='UNKNOWN'||ht.trend==='NEUTRAL')return null;let dir=ht.trend==='BULLISH'?'BUY':'SELL';let h=s.h.at(-1),h0=s.h.at(-2),l=s.l.at(-1),l0=s.l.at(-2);if(!h||!h0||!l||!l0)return null;let trend=dir==='BUY'?(h.p>h0.p&&l.p>l0.p):(h.p<h0.p&&l.p<l0.p);if(!trend)return null;let sw=findSweep(d,dir,h,l);if(!sw)return null;let ms=mssAfterSweep(d,dir,sw.i,h,l);if(!ms)return null;let f=freshFvg(d,dir,ms.i);if(!f||!inZone(c,f))return null;let fib=nearestFib(d,dir,l.p,h.p);if(!fib||!fib.ok||fib.best===.618)return null;let body=Math.abs(c.close-c.open),range=Math.max(c.high-c.low,.00001),disp=body/range>=.6&&range>=a*1.0; if(!disp)return null;let age=d.length-1-ms.i;if(age>2)return null;let rsiOK=dir==='BUY'?rv>=50&&rv<=68:rv>=32&&rv<=50;if(!rsiOK)return null;let sl=dir==='BUY'?Math.min(f.low,sw.level)-a*.2:Math.max(f.high,sw.level)+a*.2,entry=c.close,risk=Math.abs(entry-sl);if(risk<a*.5||risk>a*1.8)return null;let score=10+(fib.best===.705||fib.best===.786?2:0)+(disp?1:0);return{direction:dir,entry,sl,tp1:dir==='BUY'?entry+risk:entry-risk,tp2:dir==='BUY'?entry+2*risk:entry-2*risk,tp3:dir==='BUY'?entry+3*risk:entry-3*risk,score,atr:a,rsi:rv,m15:ht.trend,structure:dir,bos:true,mss:true,sweep:true,ob:true,fvg:true,zone:f.type,confirmation:true,displacement:true,fibNear:fib.best,fib705Distance:Math.abs(c.close-fib.levels[.705]),fib786Distance:Math.abs(c.close-fib.levels[.786]),fibLevels:{.618:fib.levels[.618],.705:fib.levels[.705],.786:fib.levels[.786]},candleTime:c.time,diagnostic:{model:'V7.1 Raid -> MSS -> displacement FVG -> OTE',sweepIndex:sw.i,mssIndex:ms.i,fvgIndex:f.i,displacementAge:age,htfRequired:true,m15NeutralBlocked:true,rsiGate:true,oteGate:true,slBasis:'sweep/FVG + ATR buffer'}}}
module.exports={analyzeV71};
