const fs=require('fs');const {getHistoricalRates}=require('dukascopy-node');
function ema(d,len){if(d.length<len)return null;const k=2/(len+1);let e=d[0].close;for(let i=1;i<d.length;i++)e+=(d[i].close-e)*k;return e}
function atr(d,len=14){if(d.length<len+1)return null;let t=[];for(let i=1;i<d.length;i++)t.push(Math.max(d[i].high-d[i].low,Math.abs(d[i].high-d[i-1].close),Math.abs(d[i].low-d[i-1].close)));return t.slice(-len).reduce((a,b)=>a+b,0)/len}
function rsi(d,len=14){if(d.length<len+1)return null;let g=0,l=0;for(let i=d.length-len;i<d.length;i++){const x=d[i].close-d[i-1].close;if(x>=0)g+=x;else l-=x}return l===0?100:100-100/(1+g/l)}
function sh(d,i,s=2){if(i<s||i>=d.length-s)return false;for(let j=i-s;j<=i+s;j++)if(j!==i&&d[j].high>=d[i].high)return false;return true}
function sl(d,i,s=2){if(i<s||i>=d.length-s)return false;for(let j=i-s;j<=i+s;j++)if(j!==i&&d[j].low<=d[i].low)return false;return true}
function swings(d){let h=[],l=[];for(let i=2;i<d.length-2;i++){if(sh(d,i))h.push({i,p:d[i].high});if(sl(d,i))l.push({i,p:d[i].low})}return{h,l}}
function m15(d){let m=[];for(const c of d){const t=Math.floor(c.time/900000)*900000,x=m.at(-1);if(!x||x.time!==t)m.push({time:t,open:c.open,high:c.high,low:c.low,close:c.close});else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close}}if(!m.length)return{trend:'UNKNOWN',bars:m};const last=d.at(-1).time,b=m.at(-1);if(b.time+900000>last+300000)m.pop();if(m.length<50)return{trend:'UNKNOWN',bars:m};const e20=ema(m,20),e50=ema(m,50),c=m.at(-1).close;return{trend:c>e20&&e20>e50?'BULLISH':c<e20&&e20<e50?'BEARISH':'NEUTRAL',bars:m}}
function fvgAt(d,dir,i){if(i<2)return null;const a=d[i-2],c=d[i];if(dir==='BUY'&&c.low>a.high)return{low:a.high,high:c.low,type:'BULLISH FVG',i};if(dir==='SELL'&&c.high<a.low)return{low:c.high,high:a.low,type:'BEARISH FVG',i};return null}
function findFvg(d,dir,ms){for(let i=ms;i<=Math.min(ms+1,d.length-1);i++){const f=fvgAt(d,dir,i);if(!f)continue;let touched=false;for(let j=f.i+1;j<d.length-1;j++)if(d[j].low<=f.high&&d[j].high>=f.low){touched=true;break}if(!touched)return f}return null}
function lastOpposingOB(d,dir,ms){for(let i=ms-1;i>=Math.max(0,ms-8);i--){const c=d[i];if(dir==='BUY'&&c.close<c.open)return{low:c.low,high:c.high,type:'BULLISH OB',i};if(dir==='SELL'&&c.close>c.open)return{low:c.low,high:c.high,type:'BEARISH OB',i}}return null}
function overlaps(a,b){return a&&b&&a.high>=b.low&&a.low<=b.high}
function fibOTE(dir,low,high,c,a){const range=high-low;if(!(range>0))return null;const levels={};for(const x of [.618,.705,.786])levels[x]=dir==='BUY'?high-range*x:low+range*x;let best=null,dist=Infinity;for(const x of [.705,.786]){const q=Math.abs(c.close-levels[x]);if(q<dist){dist=q;best=x}}return{levels,best,dist,ok:dist<=Math.max(range*.05,a*.35)}}
const names=['history180','atr_rsi','m15_not_neutral','structure','htf_alignment','liquidity_sweep','mss_displacement','fresh_fvg','fvg_overlap','ob_fvg_overlap','ote_705_786','displacement_age','rsi_range','risk','target'];
function diagnose(d){const r=Object.fromEntries(names.map(n=>[n,0]));if(d.length<180)return r;r.history180++;const c=d.at(-1),a=atr(d),rv=rsi(d),s=swings(d),ht=m15(d);if(!a||rv==null){return r}r.atr_rsi++;if(ht.trend==='UNKNOWN'||ht.trend==='NEUTRAL')return r;r.m15_not_neutral++;const dir=ht.trend==='BULLISH'?'BUY':'SELL';const preH=s.h.at(-2),preL=s.l.at(-2),curH=s.h.at(-1),curL=s.l.at(-1);if(!preH||!preL||!curH||!curL)return r;r.structure++;const trend=dir==='BUY'?curH.p>preH.p&&curL.p>preL.p:curH.p<preH.p&&curL.p<preL.p;if(!trend)return r;r.htf_alignment++;const end=d.length-1;let sw=null;for(let i=Math.max(4,end-5);i<=end;i++){if(dir==='BUY'&&d[i].low<curL.p&&d[i].close>curL.p)sw={i,level:curL.p};if(dir==='SELL'&&d[i].high>curH.p&&d[i].close<curH.p)sw={i,level:curH.p}}if(!sw)return r;r.liquidity_sweep++;const opp=dir==='BUY'?preH.p:preL.p;let ms=null;for(let i=sw.i+1;i<=Math.min(end,sw.i+4);i++){const x=d[i],body=Math.abs(x.close-x.open),rng=Math.max(x.high-x.low,.00001),disp=body/rng>=.6&&rng>=a*.9;if(dir==='BUY'&&x.close>opp&&x.close>x.open&&disp){ms={i,level:opp};break}if(dir==='SELL'&&x.close<opp&&x.close<x.open&&disp){ms={i,level:opp};break}}if(!ms)return r;r.mss_displacement++;const f=findFvg(d,dir,ms.i);if(!f)return r;r.fresh_fvg++;if(!overlaps(c,f))return r;r.fvg_overlap++;const ob=lastOpposingOB(d,dir,ms.i);if(!ob||!overlaps(ob,f))return r;r.ob_fvg_overlap++;const legLow=dir==='BUY'?sw.level:ms.level,legHigh=dir==='BUY'?ms.level:sw.level;const fib=fibOTE(dir,Math.min(legLow,legHigh),Math.max(legLow,legHigh),c,a);if(!fib||!fib.ok)return r;r.ote_705_786++;const age=end-ms.i;if(age>2)return r;r.displacement_age++;const rsiOK=dir==='BUY'?rv>=50&&rv<=68:rv>=32&&rv<=50;if(!rsiOK)return r;r.rsi_range++;const sl=dir==='BUY'?Math.min(sw.level,f.low,ob.low)-a*.2:Math.max(sw.level,f.high,ob.high)+a*.2,entry=c.close,risk=Math.abs(entry-sl);if(risk<a*.5||risk>a*1.8)return r;r.risk++;const target=dir==='BUY'?Math.max(curH.p,entry+3*risk):Math.min(curL.p,entry-3*risk);if(Math.abs(target-entry)<risk*2.5)return r;r.target++;return r}
async function load(){const to=new Date(),from=new Date(to.getTime()-30*86400000);const raw=await getHistoricalRates({instrument:'xauusd',dates:{from,to},timeframe:'m5',format:'json'});return raw.map(x=>({time:+x.timestamp,open:+x.open,high:+x.high,low:+x.low,close:+x.close})).filter(x=>Object.values(x).every(Number.isFinite)).sort((a,b)=>a.time-b.time)}
function run(d,start,end){const totals=Object.fromEntries(names.map(n=>[n,0]));for(let i=Math.max(start,180);i<end;i++){const x=diagnose(d.slice(0,i+1));for(const n of names)totals[n]+=x[n]===1?1:0}return totals}
(async()=>{const d=await load();if(d.length<2000)throw Error('Insufficient candles: '+d.length);const cut=Math.floor(d.length*2/3);const IS=run(d,0,cut),OOS=run(d,cut,d.length),ALL=run(d,0,d.length);const out={strategy:'V7.1',diagnostic:'Gate-by-Gate; exact gate order mirrored from strategy_v71.js; no strategy parameters changed',source:'Dukascopy XAUUSD M5',candles:d.length,periodStart:d[0].time,periodEnd:d.at(-1).time,split:'first 2/3 IS; final 1/3 OOS',gatePassCounts:{IS,OOS,ALL},finalTradeCandidates:{IS:IS.target,OOS:OOS.target,ALL:ALL.target}};fs.writeFileSync('backtest/v71_gate_diagnostic.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))})().catch(e=>{console.error(e);process.exit(1)})
