const fs=require('fs');
const {getHistoricalRates}=require('dukascopy-node');
const FROM=new Date('2026-03-06T00:00:00.000Z'),TO=new Date('2026-09-02T23:59:59.000Z');
async function load(){const raw=await getHistoricalRates({instrument:'xauusd',dates:{from:FROM,to:TO},timeframe:'m5',format:'json'});return raw.map(x=>({time:+x.timestamp,open:+x.open,high:+x.high,low:+x.low,close:+x.close})).filter(x=>Object.values(x).every(Number.isFinite)).sort((a,b)=>a.time-b.time)}
function getAnalyze(){const src=fs.readFileSync('strategy_v71.js','utf8'),m={exports:{}};new Function('module','exports',src)(m,m.exports);return m.exports.analyzeV71}
function proxyPrefix(d,end,accesses){return new Proxy(d.slice(0,end+1),{get(t,k,r){if(typeof k==='string'&&/^\d+$/.test(k))accesses.push(+k);return Reflect.get(t,k,r)}})}
function key(s){return s?JSON.stringify({direction:s.direction,entry:s.entry,sl:s.sl,tp1:s.tp1,tp2:s.tp2,tp3:s.tp3,fibNear:s.fibNear,candleTime:s.candleTime,diagnostic:s.diagnostic}):null}
function overlap(a,b){return a.low<=b.high&&a.high>=b.low}
function fvgAt(d,dir,i){if(i<2)return null;const a=d[i-2],c=d[i];if(dir==='BUY'&&c.low>a.high)return{low:a.high,high:c.low,type:'BULLISH FVG'};if(dir==='SELL'&&c.high<a.low)return{low:c.high,high:a.low,type:'BEARISH FVG'};return null}
(async()=>{const d=await load(),analyze=getAnalyze(),diag=JSON.parse(fs.readFileSync('backtest/v71_gate_diagnostic.json','utf8')),targets=diag.modes.NO_OTE.ALL.examples,cut=diag.splitIndex;const buckets={IS:[],OOS:[],ALL:[]};for(const t of targets){const i=d.findIndex(c=>new Date(c.time).toISOString()===t.time);if(i<0)throw Error('target candle missing '+t.time);const accesses=[];const s=analyze(proxyPrefix(d,i,accesses));const b=i<cut?'IS':'OOS';const rec={index:i,time:t.time,expectedDir:t.dir,signal:!!s,dir:s?.direction||null,accessedFuture:accesses.filter(x=>x>i),fvgIndex:s?.diagnostic?.fvgIndex??null,mssIndex:s?.diagnostic?.mssIndex??null,sweepIndex:s?.diagnostic?.sweepIndex??null,displacementAge:s?.diagnostic?.displacementAge??null,violation:false};if(!s||s.direction!==t.dir) {rec.violation=true;rec.reason='target_signal_mismatch'} if(rec.accessedFuture.length){rec.violation=true;rec.reason='future_array_access'} if(s){const f=fvgAt(d,s.direction,rec.fvgIndex);if(!f){rec.violation=true;rec.reason='invalid_fvg'}else{if(rec.fvgIndex>i||rec.fvgIndex<rec.mssIndex){rec.violation=true;rec.reason='fvg_index_out_of_bounds'}if(overlap(d[i],f)===false){rec.violation=true;rec.reason='fvg_not_overlapped_at_signal'}for(let j=rec.fvgIndex+1;j<i;j++)if(overlap(d[j],f)){rec.violation=true;rec.reason='fvg_touched_before_signal';rec.firstTouchIndex=j;break}}if(rec.displacementAge!==i-rec.mssIndex){rec.violation=true;rec.reason='displacement_age_mismatch'}}const base=key(analyze(d.slice(0,i+1)));const mutated=d.map((c,j)=>j>i?{...c,open:c.open+1000,high:c.high+2000,low:c.low-2000,close:c.close-1500}:c);const replay=key(analyze(mutated.slice(0,i+1)));rec.futureSuffixInvariant=(base===replay);if(!rec.futureSuffixInvariant){rec.violation=true;rec.reason='future_suffix_invariance_violation'}buckets[b].push(rec);buckets.ALL.push(rec)}
function sum(a){return{checked:a.length,violations:a.filter(x=>x.violation).length,signals:a.filter(x=>x.signal).length,details:a}}
const source=fs.readFileSync('strategy_v71.js','utf8');const sourceChecks={streamReplayUsesPrefix:source.includes('analyze(d.slice(0,i+1))')?'confirmed in diagnostic runner':'not in strategy source',swingWindowBound:'swings uses i<d.length-2 and sh/sl only through i+2 => max source index is end',fvgFormationBound:'fvgAt uses i-2 and i; findFvg only i=ms..ms+1',fvgTouchBound:'findFvg touch scan ends at d.length-1, which is the current signal candle'};
const result={test:'Explicit Fresh-FVG Runtime Audit + Future-Bar Invariance',strategy:'V7.1',source:'Dukascopy XAUUSD M5',candles:d.length,splitIndex:cut,targets:targets.length,IS:sum(buckets.IS),OOS:sum(buckets.OOS),ALL:sum(buckets.ALL),sourceChecks};fs.writeFileSync('backtest/v71_explicit_lookahead_fast.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2))})().catch(e=>{console.error(e);process.exit(1)})
