const fs=require('fs');
const {getHistoricalRates}=require('dukascopy-node');
const FROM=new Date('2026-03-06T00:00:00.000Z'),TO=new Date('2026-09-02T23:59:59.000Z');
async function load(){const raw=await getHistoricalRates({instrument:'xauusd',dates:{from:FROM,to:TO},timeframe:'m5',format:'json'});return raw.map(x=>({time:+x.timestamp,open:+x.open,high:+x.high,low:+x.low,close:+x.close})).filter(x=>Object.values(x).every(Number.isFinite)).sort((a,b)=>a.time-b.time)}
function loadAnalyze(){const src=fs.readFileSync('strategy_v71.js','utf8'),m={exports:{}};new Function('module','exports',src)(m,m.exports);return m.exports.analyzeV71}
function wrapPrefix(d,end,accesses){const p=d.slice(0,end+1);return new Proxy(p,{get(t,k,r){if(typeof k==='string'&&/^\d+$/.test(k))accesses.push(+k);return Reflect.get(t,k,r)}})}
function sigKey(s){if(!s)return null;return JSON.stringify({direction:s.direction,entry:s.entry,sl:s.sl,tp1:s.tp1,tp2:s.tp2,tp3:s.tp3,fibNear:s.fibNear,candleTime:s.candleTime,diagnostic:s.diagnostic})}
function fvgAt(d,dir,i){if(i<2)return null;const a=d[i-2],c=d[i];if(dir==='BUY'&&c.low>a.high)return{low:a.high,high:c.low,type:'BULLISH FVG',i};if(dir==='SELL'&&c.high<a.low)return{low:c.high,high:a.low,type:'BEARISH FVG',i};return null}
function overlap(c,f){return c.low<=f.high&&c.high>=f.low}
function summarize(arr){return{signals:arr.length,BUY:arr.filter(x=>x.dir==='BUY').length,SELL:arr.filter(x=>x.dir==='SELL').length,violations:arr.filter(x=>x.violation).length,examples:arr.filter(x=>x.violation).slice(0,20)}}
(async()=>{const d=await load(),analyze=loadAnalyze(),cut=Math.floor(d.length*2/3),buckets={IS:[],OOS:[],ALL:[]};
for(let i=180;i<d.length;i++){const accesses=[];let s=null,error=null;try{s=analyze(wrapPrefix(d,i,accesses))}catch(e){error=String(e)};const bucket=i<cut?'IS':'OOS';const rec={index:i,time:new Date(d[i].time).toISOString(),dir:s?.direction||null,violation:false};if(error){rec.violation=true;rec.reason='runtime_error';rec.error=error}else if(Math.max(-1,...accesses)>i){rec.violation=true;rec.reason='future_array_access';rec.maxAccess=Math.max(...accesses);rec.accesses=accesses.filter(x=>x>i)}else if(s){const q=s.diagnostic||{},fi=q.fvgIndex,mi=q.mssIndex,si=q.sweepIndex;rec.fvgIndex=fi;rec.mssIndex=mi;rec.sweepIndex=si;rec.displacementAge=q.displacementAge;if(!Number.isInteger(fi)||fi>i||fi<mi){rec.violation=true;rec.reason='invalid_fvg_index'}else{const f=fvgAt(d,s.direction,fi);if(!f||!overlap(d[i],f)){rec.violation=true;rec.reason='fvg_not_currently_overlapped'}else{for(let j=fi+1;j<i;j++){if(overlap(d[j],f)){rec.violation=true;rec.reason='fresh_fvg_already_touched';rec.firstTouchViolationIndex=j;break}}}}if(!rec.violation&&q.displacementAge!==i-mi){rec.violation=true;rec.reason='age_mismatch'}}
rec.signal=!!s;buckets[bucket].push(rec);buckets.ALL.push(rec)}
// Explicit future-bar invariance: take every signal target i and compare the production prefix result with the same target prefix after appending a deliberately mutated future suffix. Production analyze must not receive suffix data; any change is therefore forbidden. This is paired with the Proxy access audit above, which detects attempted out-of-prefix numeric reads.
const invariance={IS:{checked:0,violations:0,examples:[]},OOS:{checked:0,violations:0,examples:[]},ALL:{checked:0,violations:0,examples:[]}};
for(const r of buckets.ALL.filter(x=>x.signal)){const i=r.index,key=r.time,b=i<cut?'IS':'OOS';const base=sigKey(analyze(d.slice(0,i+1)));const mutated=d.slice();for(let j=i+1;j<Math.min(d.length,i+101);j++){const c={...mutated[j]};c.open+=777;c.high+=999;c.low-=999;c.close-=555;mutated[j]=c}const replay=sigKey(analyze(mutated.slice(0,i+1)));invariance[b].checked++;invariance.ALL.checked++;if(base!==replay){const ex={index:i,time:key,reason:'future_suffix_invariance_violation',base,replay};invariance[b].violations++;invariance.ALL.violations++;invariance[b].examples.push(ex);invariance.ALL.examples.push(ex)}}
const result={test:'Fresh-FVG Runtime Audit + Explicit Future-Bar Invariance / Look-ahead Test',strategy:'V7.1',source:'Dukascopy XAUUSD M5',candles:d.length,periodStart:new Date(d[0].time).toISOString(),periodEnd:new Date(d.at(-1).time).toISOString(),splitIndex:cut,rule:'Signal at index i may only access candle indices <= i; Fresh-FVG must be formed by <= i and untouched by candles between formation and signal.',freshFvg:{IS:summarize(buckets.IS),OOS:summarize(buckets.OOS),ALL:summarize(buckets.ALL)},futureBarInvariance:invariance};fs.writeFileSync('backtest/v71_fresh_fvg_lookahead_audit.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2))})().catch(e=>{console.error(e);process.exit(1)})
