const FIB_RETR=[0.618,0.65,0.705,0.786,0.886];
function swings(src,lb=2){const out=[];for(let i=lb;i<src.length-lb;i++){let hi=true,lo=true;for(let j=1;j<=lb;j++){if(src[i].high<=src[i-j].high||src[i].high<src[i+j].high)hi=false;if(src[i].low>=src[i-j].low||src[i].low>src[i+j].low)lo=false}if(hi)out.push({type:'H',price:src[i].high,time:src[i].time,index:i});if(lo)out.push({type:'L',price:src[i].low,time:src[i].time,index:i})}return out}
function structure(src){const s=swings(src.slice(-180)),h=s.filter(x=>x.type==='H'),l=s.filter(x=>x.type==='L');if(h.length<2||l.length<2)return'UNKNOWN';const hh=h.at(-1).price>h.at(-2).price,hl=l.at(-1).price>l.at(-2).price,lh=h.at(-1).price<h.at(-2).price,ll=l.at(-1).price<l.at(-2).price;if(hh&&hl)return'BULLISH';if(lh&&ll)return'BEARISH';return'RANGE'}
function aggregate(src,minutes){const step=minutes*60000,out=[];for(const x of src){const t=Math.floor(x.time/step)*step,last=out.at(-1);if(!last||last.time!==t)out.push({time:t,open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume||0});else{last.high=Math.max(last.high,x.high);last.low=Math.min(last.low,x.low);last.close=x.close;last.volume+=(x.volume||0)}}return out}
function displacement(c,minBody=.5){const r=Math.max(c.high-c.low,1e-9),b=Math.abs(c.close-c.open);return b/r>=minBody}
function fibContext(src,direction){const s=swings(src.slice(-220)),h=s.filter(x=>x.type==='H').at(-1),l=s.filter(x=>x.type==='L').at(-1);if(!h||!l||h.time===l.time)return null;const range=Math.abs(h.price-l.price),up=h.time>l.time,levels=Object.fromEntries(FIB_RETR.map(r=>[r,up?l.price+range*r:h.price-range*r])),price=src.at(-1).close,tol=Math.max(range*.025,.6),near=FIB_RETR.map(r=>({level:r,price:levels[r],dist:Math.abs(price-levels[r])})).filter(x=>x.dist<=tol).sort((a,b)=>a.dist-b.dist)[0]||null;return{near,zone618786:Boolean(near&&near.level>=.618&&near.level<=.786&&price<=Math.max(h.price,l.price)&&price>=Math.min(h.price,l.price)),levels,range,anchorHigh:h.price,anchorLow:l.price}}
function findSweep(src,direction){const i=src.length-2;if(i<12)return null;const x=src[i],prior=src.slice(i-12,i),level=direction==='BUY'?Math.min(...prior.map(c=>c.low)):Math.max(...prior.map(c=>c.high)),swept=direction==='BUY'?x.low<level&&x.close>level:x.high>level&&x.close<level;if(!swept)return null;const confirm=src.at(-1),prior3=src.slice(i-3,i),h3=Math.max(...prior3.map(c=>c.high)),l3=Math.min(...prior3.map(c=>c.low)),mss=direction==='BUY'?confirm.close>h3:confirm.close<l3,penetration=direction==='BUY'?level-x.low:x.high-level,sweptRange=Math.max(x.high-x.low,1e-9);if(!mss||!displacement(confirm,.5)||penetration/sweptRange<.10)return null;return{index:i,level,sweep:x,mssCandle:confirm,penetration}}
function latestStructureBreak(src,direction){const s=swings(src.slice(-180)),hs=s.filter(x=>x.type==='H'),ls=s.filter(x=>x.type==='L');if(direction==='BUY'){const level=hs.at(-1);return level&&src.at(-1).close>level.price?{level}:null}const level=ls.at(-1);return level&&src.at(-1).close<level.price?{level}:null}
function findFvg(src,direction){for(let i=src.length-1;i>=Math.max(2,src.length-10);i--){const a=src[i-2],x=src[i];if(direction==='BUY'&&x.low>a.high)return{low:a.high,high:x.low,time:x.time};if(direction==='SELL'&&x.high<a.low)return{low:x.high,high:a.low,time:x.time}}return null}
function findOB(src,direction){for(let i=src.length-2;i>=Math.max(0,src.length-12);i--){const x=src[i];if(direction==='BUY'&&x.close<x.open)return{low:x.low,high:x.high,time:x.time};if(direction==='SELL'&&x.close>x.open)return{low:x.low,high:x.high,time:x.time}}return null}
function targetLiquidity(src,direction,entry,risk){const s=swings(src.slice(-220)),candidates=s.filter(x=>direction==='BUY'?x.type==='H'&&x.price>entry:x.type==='L'&&x.price<entry).map(x=>x.price).sort((a,b)=>direction==='BUY'?a-b:b-a),valid=candidates.filter(p=>(direction==='BUY'?p-entry:entry-p)>=risk*1.2),tp1=valid[0]??null,tp2=valid.find(p=>tp1===null||(direction==='BUY'?p>tp1:p<tp1))??null;if(tp1===null)return null;return{tp1,tp2:tp2??(direction==='BUY'?tp1+risk:tp1-risk)}}
function makeSignal(src){if(src.length<400)return null;const c=src.at(-1),m15=aggregate(src,15),h1=aggregate(src,60),h4=aggregate(src,240);if(m15.length<30||h1.length<20||h4.length<10)return null;const st15=structure(m15),st1=structure(h1),st4=structure(h4),results=[];for(const direction of['BUY','SELL']){const aligned=direction==='BUY'?(st15==='BULLISH'&&st1!=='BEARISH'):(st15==='BEARISH'&&st1!=='BULLISH'),disp=displacement(c,.5),fib=fibContext(src,direction),sweep=findSweep(src,direction),bos=latestStructureBreak(src,direction),fvg=findFvg(src,direction),ob=findOB(src,direction);
// Continuation: M15/H1 alignment + BOS + displacement + immediate OB/FVG retest + target space.
if(aligned&&bos&&disp){const retest=Boolean((fvg&&c.close>=fvg.low&&c.close<=fvg.high)||(ob&&c.close>=ob.low&&c.close<=ob.high));if(retest){const s=swings(src.slice(-180)),lows=s.filter(x=>x.type==='L'&&x.price<c.close),highs=s.filter(x=>x.type==='H'&&x.price>c.close),invalid=direction==='BUY'?(lows.at(-1)?.price??Math.min(...src.slice(-12).map(x=>x.low))):(highs.at(-1)?.price??Math.max(...src.slice(-12).map(x=>x.high))),risk=direction==='BUY'?c.close-invalid:invalid-c.close;if(risk>0){const t=targetLiquidity(src,direction,c.close,risk);if(t)results.push({direction,setup:'CONTINUATION',path:'continuation',entry:c.close,sl:invalid,tp1:t.tp1,tp2:t.tp2,h4:st4,h1:st1,m15:st15,bos:true,sweep:false,mss:false,displacement:true,ob:Boolean(ob),fvg:Boolean(fvg),fib:fib?.near??null,retest:true,candleTime:c.time})}}}
// Liquidity/Reversal: prior-candle sweep -> current-candle MSS + displacement + 0.618-0.786 Fib zone. BOS is deliberately not required.
if(sweep&&fib?.zone618786){const invalid=direction==='BUY'?sweep.sweep.low:sweep.sweep.high,risk=direction==='BUY'?c.close-invalid:invalid-c.close;if(risk>0){const t=targetLiquidity(src,direction,c.close,risk);if(t)results.push({direction,setup:'LIQUIDITY_REVERSAL',path:'reversal',entry:c.close,sl:invalid,tp1:t.tp1,tp2:t.tp2,h4:st4,h1:st1,m15:st15,bos:false,sweep:true,mss:true,displacement:true,ob:Boolean(ob),fvg:Boolean(fvg),fib:fib.near,retest:true,candleTime:c.time})}}}
if(results.length!==1)return null;return results[0]}
module.exports={makeSignal,aggregate,structure,swings};
