const fs=require('fs');const{getHistoricalRates}=require('dukascopy-node');
const DAYS=540,SPLIT_FRAC=2/3,SWINGS=[3,5,7,10];
function sess(t){const d=new Date(t);const h=d.getUTCHours()+d.getUTCMinutes()/60;return h>=7&&h<11?'LONDON':h>=13&&h<17?'NEW_YORK':'OTHER'}
function clean(raw){return raw.map(x=>({time:+x.timestamp,open:+x.open,high:+x.high,low:+x.low,close:+x.close})).filter(x=>Object.values(x).every(Number.isFinite))}
async function fetchChunk(instrument,timeframe,from,to){let last;for(let attempt=1;attempt<=4;attempt++){try{return clean(await getHistoricalRates({instrument,dates:{from,to},timeframe,format:'json'}))}catch(e){last=e;console.log(`fetch retry ${attempt}/4 ${timeframe}: ${e.message}`);await new Promise(r=>setTimeout(r,1500*attempt))}}throw last}
async function load(tf){const to=new Date(),from=new Date(to-DAYS*86400000),rows=[];let cur=new Date(from);while(cur<to){const end=new Date(Math.min(cur.getTime()+45*86400000,to.getTime()));const part=await fetchChunk('xauusd',tf,cur,end);rows.push(...part);console.log(`loaded ${tf} ${cur.toISOString()} -> ${end.toISOString()} rows=${part.length}`);cur=end;await new Promise(r=>setTimeout(r,500))}const m=new Map();for(const x of rows)m.set(x.time,x);return [...m.values()].sort((a,b)=>a.time-b.time)}
function atr(d,n=14){if(d.length<n+1)return null;let s=0;for(let i=d.length-n;i<d.length;i++){const p=d[i-1],c=d[i];s+=Math.max(c.high-c.low,Math.abs(c.high-p.close),Math.abs(c.low-p.close))}return s/n}
function swings(d,s){const h=[],l=[];for(let i=s;i<d.length-s;i++){let hi=1,lo=1;for(let j=1;j<=s;j++){if(d[i-j].high>=d[i].high||d[i+j].high>=d[i].high)hi=0;if(d[i-j].low<=d[i].low||d[i+j].low<=d[i].low)lo=0}if(hi)h.push({i,p:d[i].high,confirmedAt:i+s});if(lo)l.push({i,p:d[i].low,confirmedAt:i+s})}return{h,l}}
function bias(d,s){const x=swings(d,s);if(x.h.length<2||x.l.length<2)return null;const hh=x.h.at(-1).p>x.h.at(-2).p,hl=x.l.at(-1).p>x.l.at(-2).p,lh=x.h.at(-1).p<x.h.at(-2).p,ll=x.l.at(-1).p<x.l.at(-2).p;return hh&&hl?'BUY':lh&&ll?'SELL':null}
function ob(d,dir,end){for(let i=end-1;i>=Math.max(0,end-12);i--){const c=d[i];if(dir==='BUY'&&c.close<c.open)return c;if(dir==='SELL'&&c.close>c.open)return c}return null}
function confirm(d,dir){if(d.length<2)return false;const p=d.at(-2),c=d.at(-1),body=Math.abs(c.close-c.open),u=c.high-Math.max(c.open,c.close),lo=Math.min(c.open,c.close)-c.low;const eng=dir==='BUY'?c.close>c.open&&p.close<p.open&&c.open<=p.close&&c.close>=p.open:c.close<c.open&&p.close>p.open&&c.open>=p.close&&c.close<=p.open;const pin=dir==='BUY'?lo>=body*2&&u<=body:u>=body*2&&lo<=body;return eng||pin}
function stats(a){let eq=0,peak=0,dd=0,ls=0,maxls=0;for(const t of a){eq+=t.R;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq);ls=t.R<0?ls+1:0;maxls=Math.max(maxls,ls)}const w=a.filter(x=>x.R>0),l=a.filter(x=>x.R<0),gw=w.reduce((s,x)=>s+x.R,0),gl=Math.abs(l.reduce((s,x)=>s+x.R,0)),net=eq;return{trades:a.length,wins:w.length,losses:l.length,winRate:+(100*w.length/(a.length||1)).toFixed(2),netR:+net.toFixed(3),profitFactor:+(gw/(gl||1)).toFixed(3),expectancy:+(net/(a.length||1)).toFixed(3),maxDrawdownR:+dd.toFixed(3),maxLosingStreak:maxls}}
function detailStats(a){const base=stats(a),days=[...new Set(a.map(x=>x.day))].length;const rDist={minus1:a.filter(x=>x.R===-1).length,plus2:a.filter(x=>x.R===2).length};const monthly={};for(const t of a){const m=t.day.slice(0,7);monthly[m]??=[];monthly[m].push(t)}return{...base,daysWithTrades:days,avgTradesPerDay:+(a.length/(days||1)).toFixed(3),rDistribution:rDist,byDirection:{BUY:stats(a.filter(x=>x.direction==='BUY')),SELL:stats(a.filter(x=>x.direction==='SELL'))},monthly:Object.fromEntries(Object.entries(monthly).map(([k,v])=>[k,stats(v)])),trades:a}}
function sim(d,start,end,s,sessionOnly){const ts=[];for(let i=Math.max(100,start);i<end-1;i++){const pre=d.slice(0,i+1),dir=bias(pre,s);if(!dir)continue;if(sessionOnly&&sess(d[i].time)!==sessionOnly)continue;const sw=swings(pre,s),hs=sw.h.filter(x=>x.confirmedAt<=i),ls=sw.l.filter(x=>x.confirmedAt<=i);if(hs.length<2||ls.length<2)continue;const level=dir==='BUY'?hs.at(-1).p:ls.at(-1).p;let bos=false;for(let k=Math.max(0,i-6);k<=i;k++)if(dir==='BUY'?pre[k].close>level:pre[k].close<level){bos=true;break}if(!bos||!confirm(pre,dir))continue;const z=ob(pre,dir,i),a=atr(pre);if(!z||!a)continue;const entry=d[i+1].open,sl=dir==='BUY'?z.low-a*.2:z.high+a*.2,risk=Math.abs(entry-sl);if(!(risk>0))continue;const tp=dir==='BUY'?entry+2*risk:entry-2*risk;let R=null,bars=0;for(let j=i+1;j<end;j++){bars++;const c=d[j];if(dir==='BUY'){if(c.low<=sl){R=-1;break}if(c.high>=tp){R=2;break}}else{if(c.high>=sl){R=-1;break}if(c.low<=tp){R=2;break}}}if(R===null)continue;ts.push({day:new Date(d[i].time).toISOString().slice(0,10),direction:dir,R,session:sess(d[i].time),signalTime:d[i].time});i+=Math.max(1,bars-1)}return detailStats(ts)}
async function runTF(tf){const d=await load(tf),cut=Math.floor(d.length*SPLIT_FRAC),out={timeframe:tf,candles:d.length,split:'first 2/3 IS; final 1/3 OOS; no OOS tuning',A:{IS:sim(d,250,cut,5,null),OOS:sim(d,cut,d.length,5,null),ALL:sim(d,250,d.length,5,null)},swingSensitivity:{}};for(const s of SWINGS)out.swingSensitivity[s]={IS:sim(d,250,cut,s,null),OOS:sim(d,cut,d.length,s,null),ALL:sim(d,250,d.length,s,null)};out.sessionCrossCheck={LONDON:out.A,NEW_YORK:{IS:sim(d,250,cut,5,'NEW_YORK'),OOS:sim(d,cut,d.length,5,'NEW_YORK')},LONDON_NEWYORK:{IS:sim(d,250,cut,5,null),OOS:sim(d,cut,d.length,5,null)}};return out}

const PRIOR_RUN_FROM='2025-03-15T12:32:43.402Z';
const PRIOR_RUN_TO='2026-09-06T12:32:43.402Z';
const BLIND_PREVIOUS_DATA_END=process.env.BLIND_PREVIOUS_DATA_END;
const BLIND_START=process.env.BLIND_START;
const BLIND_END=process.env.BLIND_END;
async function loadWindow(tf,fromISO,toISO){const rows=[];let cur=new Date(fromISO),to=new Date(toISO);while(cur<to){const end=new Date(Math.min(cur.getTime()+45*86400000,to.getTime()));const part=await fetchChunk('xauusd',tf,cur,end);rows.push(...part);cur=end;await new Promise(r=>setTimeout(r,500))}const m=new Map();for(const x of rows)m.set(x.time,x);return [...m.values()].sort((a,b)=>a.time-b.time)}
function blindSim(d,s,startMs,endMs){const ts=[];const startIdx=d.findIndex(x=>x.time>=startMs);const endIdx=d.findIndex(x=>x.time>=endMs);const end=endIdx<0?d.length:endIdx;for(let i=Math.max(100,startIdx);i<end-1;i++){const pre=d.slice(0,i+1),dir=bias(pre,s);if(!dir)continue;const sw=swings(pre,s),hs=sw.h.filter(x=>x.confirmedAt<=i),ls=sw.l.filter(x=>x.confirmedAt<=i);if(hs.length<2||ls.length<2)continue;const level=dir==='BUY'?hs.at(-1).p:ls.at(-1).p;let bos=false;for(let k=Math.max(0,i-6);k<=i;k++)if(dir==='BUY'?pre[k].close>level:pre[k].close<level){bos=true;break}if(!bos||!confirm(pre,dir))continue;const z=ob(pre,dir,i),a=atr(pre);if(!z||!a)continue;const entry=d[i+1].open,sl=dir==='BUY'?z.low-a*.2:z.high+a*.2,risk=Math.abs(entry-sl);if(!(risk>0))continue;const tp=dir==='BUY'?entry+2*risk:entry-2*risk;let R=null,exitIndex=null;for(let j=i+1;j<end;j++){const c=d[j];if(dir==='BUY'){if(c.low<=sl){R=-1;exitIndex=j;break}if(c.high>=tp){R=2;exitIndex=j;break}}else{if(c.high>=sl){R=-1;exitIndex=j;break}if(c.low<=tp){R=2;exitIndex=j;break}}}if(R===null)continue;ts.push({day:new Date(d[i].time).toISOString().slice(0,10),direction:dir,R,session:sess(d[i].time),signalTime:d[i].time,entry,sl,tp,exitTime:d[exitIndex].time});i+=1}return detailStats(ts)}
async function buildManifest(){const prior=await loadWindow('m15',PRIOR_RUN_FROM,PRIOR_RUN_TO);if(prior.length<1000)throw new Error('Prior dataset reproduction too small');const cut=Math.floor(prior.length*(2/3));const previousOosEnd=prior[cut-1].time;const blindStart=prior.find(x=>x.time>previousOosEnd)?.time;const now=new Date();const current=await loadWindow('m15',new Date(previousOosEnd+1).toISOString(),now.toISOString());const usable=current.filter(x=>x.time>previousOosEnd&&x.time<now.getTime());const blindEnd=usable.length?usable.at(-1).time:previousOosEnd;const manifest={schema:'v8-blind-holdout-manifest-v1',createdAt:new Date().toISOString(),previousArtifactRun:34029244986,priorDataset:{from:PRIOR_RUN_FROM,to:PRIOR_RUN_TO,candles:prior.length,split:'first 2/3 IS; final 1/3 OOS'},previousOosEnd:new Date(previousOosEnd).toISOString(),blindStart:new Date(blindStart??previousOosEnd).toISOString(),blindEnd:new Date(blindEnd).toISOString(),dataset:'Dukascopy historical rates',timeframe:'m15',variants:[7,10],strategy:'OB+Confirmation+RR2+ALL_SESSIONS',rule:'Blind score only after previousOosEnd; warmup may precede boundary but no pre-boundary trade is scored; manifest generated before scoring.'};fs.writeFileSync('backtest/blind_holdout_manifest.json',JSON.stringify(manifest,null,2));fs.writeFileSync('backtest/blind_env.json',JSON.stringify({BLIND_PREVIOUS_DATA_END:manifest.previousOosEnd,BLIND_START:manifest.blindStart,BLIND_END:manifest.blindEnd},null,2));console.log(JSON.stringify(manifest,null,2));}
async function runBlind(){if(!BLIND_PREVIOUS_DATA_END||!BLIND_START||!BLIND_END)throw new Error('Immutable blind manifest missing');const warmupStart=new Date(new Date(BLIND_START).getTime()-45*86400000).toISOString();const d=await loadWindow('m15',warmupStart,BLIND_END);const start=Date.parse(BLIND_START),end=Date.parse(BLIND_END);const variants={};for(const s of [7,10])variants[s]=blindSim(d,s,start,end);const totalCandles=d.filter(x=>x.time>=start&&x.time<end).length;return{mode:'BLIND_HOLDOUT_IMMUTABLE',strategy:'V8 CORE OB+CONFIRMATION+RR2+ALL_SESSIONS',timeframe:'m15',source:'Dukascopy historical rates',frozenVariants:[7,10],previousArtifactRun:34029244986,previousDataEnd:BLIND_PREVIOUS_DATA_END,blindStart:BLIND_START,blindEnd:BLIND_END,blindCandles:totalCandles,warmupStart,rule:'Only trades signaled and fully resolved inside [blindStart, blindEnd) are scored; pre-boundary candles are causal warmup only and never scored.',noTuningAfterResult:true,lookaheadAudit:['prefix-only signal calculation','confirmed pivots only','closed M15 signal candle','next-bar execution','SL checked before TP on same bar','no IS/OOS trade enters score','same blind dataset for both variants'],variants};}
(async()=>{if(process.env.VALIDATION_MODE==='blind_holdout'){if(!fs.existsSync('backtest/blind_env.json'))await buildManifest();const e=JSON.parse(fs.readFileSync('backtest/blind_env.json','utf8'));process.env.BLIND_PREVIOUS_DATA_END=e.BLIND_PREVIOUS_DATA_END;process.env.BLIND_START=e.BLIND_START;process.env.BLIND_END=e.BLIND_END;const out=await runBlind();fs.writeFileSync('backtest/v8_blind_holdout_result.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));return}const out={strategy:'V8 CORE OB+CONFIRMATION+RR2',source:'Dukascopy historical rates; 45-day chunks with retries',lookaheadAudit:['prefix-only signal calculation','confirmed pivots only','closed signal candle','next-bar execution','SL checked before TP on same bar','OOS never used for parameter selection'],M5:await runTF('m5'),M15:await runTF('m15')};fs.writeFileSync('backtest/v8_core_edge_validation_result.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))})().catch(e=>{console.error(e);process.exit(1)})