// Attribution diagnostic for the exact 284-trade candidate artifact. No strategy logic or main/Production changes.
const fs=require('fs');
const src=JSON.parse(fs.readFileSync('backtest/v8_candidate_result.json','utf8'));
const tr=src.ALL.details||[];
function stats(a){const n=a.length,w=a.filter(t=>t.R>0),l=a.filter(t=>t.R<0),gp=w.reduce((s,t)=>s+t.R,0),gl=Math.abs(l.reduce((s,t)=>s+t.R,0));let e=0,p=0,dd=0;for(const t of a){e+=t.R;p=Math.max(p,e);dd=Math.max(dd,p-e)}return{trades:n,wins:w.length,losses:l.length,winRate:+(100*w.length/(n||1)).toFixed(2),netR:+a.reduce((s,t)=>s+t.R,0).toFixed(3),profitFactor:+(gp/(gl||1)).toFixed(3),avgR:+(a.reduce((s,t)=>s+t.R,0)/(n||1)).toFixed(3),maxDrawdownR:+dd.toFixed(3)}}
function cohort(name,p){const a=tr.filter(p);return [name,{...stats(a),sharePct:+(100*a.length/(tr.length||1)).toFixed(2)}]}
const out={strategy:src.strategy,runBasis:'Exact 284-trade ALL detail set from V8 Candidate Relaxed Validation; no new trades generated',total:stats(tr),cohorts:Object.fromEntries([
 cohort('FVG_only',t=>t.fvg&&!t.ob),cohort('OB_only',t=>t.ob&&!t.fvg),cohort('FVG_and_OB',t=>t.fvg&&t.ob),cohort('FVG_present',t=>t.fvg),cohort('OB_present',t=>t.ob),
 cohort('confirmation_yes',t=>t.confirmation),cohort('confirmation_no',t=>!t.confirmation),cohort('OB_only_confirmation_yes',t=>t.ob&&!t.fvg&&t.confirmation),cohort('OB_only_confirmation_no',t=>t.ob&&!t.fvg&&!t.confirmation),cohort('FVG_and_OB_confirmation_yes',t=>t.fvg&&t.ob&&t.confirmation),cohort('FVG_and_OB_confirmation_no',t=>t.fvg&&t.ob&&!t.confirmation),
 cohort('ATR_lt_1',t=>t.atrRatio<1),cohort('ATR_1_to_2_2',t=>t.atrRatio>=1&&t.atrRatio<=2.2),cohort('ATR_gt_2_2',t=>t.atrRatio>2.2),cohort('BUY',t=>t.direction==='BUY'),cohort('SELL',t=>t.direction==='SELL'),cohort('LONDON',t=>t.session==='LONDON'),cohort('NEW_YORK',t=>t.session==='NEW_YORK'),cohort('score_90_100',t=>t.score>=90),cohort('score_70_89',t=>t.score>=70&&t.score<90)
]),limitations:['Stored candidate trades have bos=true and choch=false, so BOS-vs-CHOCH cannot be separated from this artifact.','Candidate has no sweep gate and trade details have no sweep flag, so sweep-removal impact cannot be quantified from these 284 records.','RR is fixed at 1.5 in every stored trade, so RR>=1.5 is constant and cannot explain cross-trade differences.','Cohorts overlap intentionally; cohort results are attribution evidence, not identical counterfactual P&L after removing one filter.'],diagnosis:['FVG_and_OB is the only positive zone cohort but has only 9 trades; not enough to declare an edge.','FVG_only is materially worse than OB_only in this sample.','Confirmation_yes is much less negative than confirmation_no, indicating confirmation should be materially weighted/required rather than treated as a weak optional score.','Score is non-discriminatory because observed candidate scores are concentrated at 90-100.']};
fs.writeFileSync('backtest/v8_candidate_attribution_result.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
