const fs = require('fs');
const { getHistoricalRates } = require('dukascopy-node');
const DAY=86400000,M5=300000,NOW=Date.now(),MIN_M5=1200,MAX_AGE=1200000,DIRECT_WINDOW=48*3600000,TIMEOUT=12000;
const inBreak=()=>new Date(NOW).getUTCHours()===21;
const ts=v=>{if(typeof v==='string'){const d=Date.parse(v);if(Number.isFinite(d))return d;}const n=Number(v);return Number.isFinite(n)?(n<1e11?n*1000:n):NaN;};
function norm(rows,source){return(rows||[]).map(r=>{const t=ts(r?.timestamp??r?.time??r?.openTime??r?.[0]),o=Number(r?.open??r?.[1]),h=Number(r?.high??r?.[2]),l=Number(r?.low??r?.[3]),c=Number(r?.close??r?.[4]),v=Number(r?.volume??r?.tickVolume??r?.[5]??0)||0;if(!Number.isFinite(t)||![o,h,l,c].every(Number.isFinite))return null;return{openTime:new Date(t).toISOString(),open:o,high:h,low:l,close:c,volume:v,source,isOpen:false};}).filter(Boolean);}
const uniq=rows=>{const m=new Map();for(const b of rows||[])m.set(b.openTime,b);return[...m.values()].sort((a,b)=>Date.parse(a.openTime)-Date.parse(b.openTime));};
const closed=rows=>uniq(rows).filter(b=>Date.parse(b.openTime)<=Math.floor(NOW/M5)*M5-M5&&!b.isOpen);
const direct=rows=>closed(rows).filter(b=>b.source==='biquote'||b.source==='xaus-spot');
const directFresh=rows=>{const d=direct(rows);if(!d.length)return false;const age=NOW-Date.parse(d.at(-1).openTime);return age>=0&&age<=MAX_AGE&&NOW-Date.parse(d[0].openTime)<=DIRECT_WINDOW;};
const fresh=rows=>{const x=closed(rows);if(x.length<MIN_M5)return false;const age=NOW-Date.parse(x.at(-1).openTime);return age>=0&&age<=MAX_AGE;};
async function text(url,headers={}){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),TIMEOUT);try{const r=await fetch(url,{headers,signal:ac.signal}),t=await r.text();if(!r.ok)throw Error(`HTTP ${r.status}: ${t.slice(0,180)}`);return t;}finally{clearTimeout(timer);}}
function cache(){try{const j=JSON.parse(fs.readFileSync('xauusd_m5.json','utf8'));const r=Array.isArray(j)?j:(j?.bars||[]);const x=norm(r,'cache');console.log(`Cached XAUUSD M5: ${x.length} rows`);return x;}catch{console.log('No usable XAUUSD M5 cache found.');return[];}}
async function biquote(){const j=JSON.parse(await text('https://biquote.io/api/XAUUSD/ohlc?interval=5m&limit=1000',{Accept:'application/json','User-Agent':'Gold-alert-bot/2.0'}));const r=Array.isArray(j)?j:(j?.bars||j?.data||j?.candles||j?.result||[]),x=norm(r,'biquote');console.log(`BiQuote direct M5: raw=${r.length||0} closed=${closed(x).length} latest=${x.at(-1)?.openTime||'none'}`);if(!x.length)throw Error('BiQuote returned no XAUUSD M5 bars');return x;}
async function xaus(){const j=JSON.parse(await text(`https://xaus.com/api/v1/intraday?symbol=xau&hours=48&fresh=${NOW}`,{Accept:'application/json','User-Agent':'Gold-alert-bot/2.0'}));if(j?.data_state?.status!=='fresh')throw Error(`XAUS intraday not fresh: ${JSON.stringify(j?.data_state||{})}`);const p=Array.isArray(j?.points)?j.points:[],g=new Map();for(const z of p){const t=ts(z?.t),price=Number(z?.p);if(!Number.isFinite(t)||!Number.isFinite(price))continue;const k=Math.floor(t/M5)*M5,a=g.get(k)||[];a.push({t,price});g.set(k,a);}const out=[];for(const[k,a]of g){a.sort((x,y)=>x.t-y.t);if(a.length<2)continue;out.push({openTime:new Date(k).toISOString(),open:a[0].price,high:Math.max(...a.map(x=>x.price)),low:Math.min(...a.map(x=>x.price)),close:a.at(-1).price,volume:0,source:'xaus-spot',isOpen:false});}const x=closed(out);console.log(`XAUS direct spot 2m->M5: points=${p.length} bars=${x.length} latest=${x.at(-1)?.openTime||'none'}`);if(!x.length)throw Error('XAUS returned no completed spot bars');return x;}
async function yahoo(spotRows){let result,last;for(const host of['query1','query2'])try{const j=JSON.parse(await text(`https://${host}.finance.yahoo.com/v8/finance/chart/GC%3DF?range=10d&interval=5m&includePrePost=true&events=div%2Csplits`,{Accept:'application/json','User-Agent':'Gold-alert-bot/2.0'}));result=j?.chart?.result?.[0];if(result)break;}catch(e){last=e;}if(!result)throw Error(`Yahoo GC=F unavailable: ${last?.message||last}`);const q=result.indicators?.quote?.[0]||{},raw=(result.timestamp||[]).map((t,i)=>({timestamp:Number(t)*1000,open:q.open?.[i],high:q.high?.[i],low:q.low?.[i],close:q.close?.[i],volume:q.volume?.[i]||0})),f=closed(norm(raw,'yahoo-gcf')),s=direct(spotRows);if(!f.length||s.length<20)throw Error(`Insufficient historical calibration: futures=${f.length}, direct=${s.length}`);const d=[];for(const b of f){let best=null;for(const a of s){const dist=Math.abs(Date.parse(a.openTime)-Date.parse(b.openTime));if(dist<=10*M5&&(!best||dist<best.dist))best={dist,close:a.close};}if(best)d.push(best.close-b.close);}if(d.length<20)throw Error(`Insufficient spot/futures overlap: ${d.length}`);d.sort((a,b)=>a-b);const basis=d[Math.floor(d.length/2)];console.log(`Yahoo GC=F historical context: bars=${f.length} overlap=${d.length} basis=${basis.toFixed(3)}`);return f.map(b=>({...b,open:b.open+basis,high:b.high+basis,low:b.low+basis,close:b.close+basis,source:'yahoo-gcf-calibrated'}));}
async function duk(days){const d=await getHistoricalRates({instrument:'xauusd',dates:{from:new Date(NOW-days*DAY),to:new Date(NOW-M5)},timeframe:'m5',priceType:'bid',format:'array',volumes:true,ignoreFlats:false,batchSize:5,pauseBetweenBatchesMs:1500,retryCount:1,pauseBetweenRetriesMs:3000,retryOnEmpty:true,failAfterRetryCount:true});return norm(Array.isArray(d)?d:d?.data,'dukascopy');}
(async()=>{let bars=cache();try{bars=uniq([...bars,...await biquote()]);}catch(e){console.log(`BiQuote failed: ${e?.stack||e}`);}try{bars=uniq([...bars,...await xaus()]);}catch(e){console.log(`XAUS direct spot failed: ${e?.stack||e}`);}console.log(`Direct XAUUSD spot bars=${direct(bars).length}; directFresh=${directFresh(bars)}`);if(!directFresh(bars))throw Error('No fresh direct XAU/USD spot decision window');if(closed(bars).length<MIN_M5){try{bars=uniq([...bars,...await yahoo(bars)]);}catch(e){console.log(`Yahoo historical context failed: ${e?.stack||e}`);}}if(closed(bars).length<MIN_M5&&!inBreak())for(const days of[2,5,10]){try{const x=closed(await duk(days));console.log(`Dukascopy M5 ${days}d: ${x.length}`);bars=uniq([...bars,...x]);if(closed(bars).length>=MIN_M5)break;}catch(e){console.log(`Dukascopy M5 ${days}d failed: ${e?.stack||e}`);}}bars=closed(bars);if(bars.length<MIN_M5)throw Error(`Insufficient XAUUSD M5 history: ${bars.length}`);const d=direct(bars),dl=d.at(-1);if(!dl||NOW-Date.parse(dl.openTime)>MAX_AGE)throw Error('Direct XAU/USD spot source is stale');const out=bars.slice(-3000);fs.writeFileSync('/tmp/xau.json',JSON.stringify({symbol:'XAUUSD',interval:'5m',bars:out,provenance:{directSpotBars:d.length,directLatest:dl.openTime,historicalProxyBars:out.filter(b=>b.source==='yahoo-gcf-calibrated').length}}));console.log(`Published ${out.length} closed XAUUSD M5 bars; directLatest=${dl.openTime}; proxyBars=${out.filter(b=>b.source==='yahoo-gcf-calibrated').length}`);})().catch(e=>{console.error(e?.stack||e);process.exit(1);});
