const fs=require('fs');
const {getHistoricalRates}=require('dukascopy-node');
const DAY=86400000,M5=300000,NOW=Date.now(),MIN_M5=1200,MAX_AGE_MS=20*60000;
function ts(v){if(typeof v==='string'){const d=Date.parse(v);if(Number.isFinite(d))return d;}const n=Number(v);return Number.isFinite(n)?(n<1e11?n*1000:n):NaN;}
function norm(rows){return(rows||[]).map(r=>{const t=ts(r?.timestamp??r?.time??r?.openTime??r?.[0]);const o=Number(r?.open??r?.[1]),h=Number(r?.high??r?.[2]),l=Number(r?.low??r?.[3]),c=Number(r?.close??r?.[4]),v=Number(r?.volume??r?.tickVolume??r?.[5]??0)||0;const isOpen=Boolean(r?.isOpen);return Number.isFinite(t)&&[o,h,l,c].every(Number.isFinite)?{openTime:new Date(t).toISOString(),open:o,high:h,low:l,close:c,volume:v,isOpen}:null}).filter(Boolean)}
function unique(a){const m=new Map();for(const b of a||[])m.set(b.openTime,b);return[...m.values()].sort((x,y)=>Date.parse(x.openTime)-Date.parse(y.openTime))}
function latest(a){return a.length?Date.parse(a.at(-1).openTime):NaN}
function fresh(a){const age=NOW-latest(a);return a.length>=MIN_M5&&age>=0&&age<=MAX_AGE_MS}
async function biquoteM5Window(from,to){const p=new URLSearchParams({interval:'5m',limit:'1000',from:new Date(from).toISOString(),to:new Date(to).toISOString()});const u=`https://biquote.io/api/XAUUSD/ohlc?${p}`;const r=await fetch(u,{headers:{Accept:'application/json','User-Agent':'Gold-alert-bot/1.0'}});const text=await r.text();if(!r.ok)throw new Error(`BiQuote HTTP ${r.status}: ${text.slice(0,180)}`);let j;try{j=JSON.parse(text)}catch(e){throw new Error(`BiQuote invalid JSON: ${e.message}`)}const rows=Array.isArray(j)?j:(j?.bars||j?.data||j?.candles||j?.result||[]);if(!Array.isArray(rows)||!rows.length)throw new Error('BiQuote returned no XAUUSD M5 bars');return norm(rows)}
async function biquoteM5(){const first=await biquoteM5Window(NOW-4*DAY,NOW-M5);console.log(`BiQuote latest window raw: ${first.length}`);const closed=first.filter(b=>!b.isOpen);console.log(`BiQuote latest window closed: ${closed.length}`);if(fresh(closed))return unique(closed);const oldest=closed.length?Date.parse(closed[0].openTime):NaN;if(!Number.isFinite(oldest))throw new Error('BiQuote returned bars but none could be parsed as closed candles');const second=await biquoteM5Window(oldest-1200*M5,oldest-M5);console.log(`BiQuote older window: ${second.length}`);const merged=unique([...closed,...second.filter(b=>!b.isOpen)]);if(!fresh(merged))throw new Error(`BiQuote M5 insufficient/freshness failure: ${merged.length} closed bars`);return merged}
async function dukM5(days){const data=await getHistoricalRates({instrument:'xauusd',dates:{from:new Date(NOW-days*DAY),to:new Date(NOW-M5)},timeframe:'m5',priceType:'bid',format:'array',volumes:true,ignoreFlats:false,batchSize:1,pauseBetweenBatchesMs:7000,retryCount:1,pauseBetweenRetriesMs:10000,retryOnEmpty:true,failAfterRetryCount:1});return norm(Array.isArray(data)?data:data?.data)}
(async()=>{let bars=[];const providers=[['BiQuote M5',()=>biquoteM5()],['Dukascopy M5 2d',()=>dukM5(2)],['Dukascopy M5 1d',()=>dukM5(1)],['Dukascopy M5 0.5d',()=>dukM5(0.5)]];for(const [name,fn] of providers){try{const got=unique(await fn());console.log(`${name}: ${got.length}`);bars=unique([...bars,...got]);if(fresh(bars))break}catch(e){console.log(`${name} failed: ${e?.stack||e?.message||String(e)}`)}}if(!fresh(bars))throw new Error(`No fresh XAUUSD M5 feed: bars=${bars.length}, latest=${Number.isFinite(latest(bars))?new Date(latest(bars)).toISOString():'none'}`);const out=bars.filter(b=>!b.isOpen).slice(-3000);fs.writeFileSync('/tmp/xau.json',JSON.stringify({symbol:'XAUUSD',interval:'5m',bars:out}));console.log(`Published ${out.length} unique fresh closed XAUUSD M5 bars`);})().catch(e=>{console.error(e.stack||e.message);process.exit(1)});
